const fs = require('fs');
let content = fs.readFileSync('src/views/CariPenyakitView.tsx', 'utf-8');

const newData = `const PENYAKIT_CATALOG = [
  // JAMUR (25)
  { nama: 'Antraknosa (Patek)', kategori: 'Jamur', penyebab: 'Colletotrichum capsici', tanaman: ['Cabai', 'Tomat', 'Kacang', 'Mangga', 'Pepaya', 'Bawang Merah'], ciriCiri: 'Bercak melingkar cekung hitam/jingga pada buah. Buah mengerut dan busuk basah atau kering.', kerugian: 'Gagal panen hingga 80%, penyebaran sangat cepat di musim hujan akibat spora memercik air.', penanganan: 'Fungisida Mankozeb, Propineb, Tiram, atau Difenokonazol. Kumpulkan dan bakar buah terinfeksi.', sasaranPestisida: 'Patek', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/77/Colletotrichum_lindemuthianum.jpg' },
  { nama: 'Layu Fusarium', kategori: 'Jamur', penyebab: 'Fusarium oxysporum', tanaman: ['Cabai', 'Tomat', 'Mentimun', 'Bawang Merah', 'Kacang', 'Semangka'], ciriCiri: 'Layu siang hari, segar pagi hari. Daun menguning bawah ke atas, tulang daun/vaskular coklat bila dibelah.', kerugian: 'Tanaman mati permanen, jamur bertahan puluhan tahun di tanah.', penanganan: 'Agen hayati Trichoderma. Fungisida Difenokonazol/Tebukonazol/Benomil kocor.', sasaranPestisida: 'Layu Fusarium', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Fusarium_wilt_symptom_tobacco.jpg/960px-Fusarium_wilt_symptom_tobacco.jpg' },
  { nama: 'Bercak Daun Cercospora', kategori: 'Jamur', penyebab: 'Cercospora capsici', tanaman: ['Cabai', 'Tomat', 'Kacang', 'Kangkung', 'Kopi', 'Kedelai'], ciriCiri: 'Bercak bulat "mata katak" (tengah abu, tepi coklat tua) di daun tua.', kerugian: 'Daun rontok (defoliasi), buah menjadi kerdil, hasil menurun karena fotosintesis berkurang.', penanganan: 'Semprot Fungisida Mankozeb, Klorotalonil, atau Azoksistrobin.', sasaranPestisida: 'Bercak Daun', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Cercospora_beticola_on_sugar_beet.jpeg/960px-Cercospora_beticola_on_sugar_beet.jpeg' },
  { nama: 'Busuk Daun Phytophthora', kategori: 'Jamur', penyebab: 'Phytophthora infestans', tanaman: ['Tomat', 'Cabai', 'Mentimun', 'Kentang', 'Kakao'], ciriCiri: 'Bercak hawar basah cepat membesar, hitam kebasahan. Jamur berbulu putih di bawah daun.', kerugian: 'Menghancurkan seluruh kebun dalam hitungan hari (musim hujan/dingin/berkabut).', penanganan: 'Fungisida sistemik Dimetomorf, Simoksanil, Propamokarb. Perbaiki drainase lahan.', sasaranPestisida: 'Busuk Daun', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Late_blight_on_potato_leaf_2.jpg/960px-Late_blight_on_potato_leaf_2.jpg' },
  { nama: 'Akar Gada (Clubroot)', kategori: 'Jamur', penyebab: 'Plasmodiophora brassicae', tanaman: ['Kubis', 'Sawi', 'Pakcoy', 'Brokoli'], ciriCiri: 'Akar bengkak seperti gada/tumor, daun pucat kemerahan layu siang hari meskipun tanah basah.', kerugian: 'Akar rusak total tidak menyerap hara, gagal panen.', penanganan: 'Naikkan pH tanah dengan kapur dolomit. Rotasi tanaman bukan famili kubis. Fungisida Flusulfamida.', sasaranPestisida: 'Akar Gada', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Knolvoet_bij_bloemkool_%28Plasmodiophora_brassicae_on_cauliflower%29.jpg/960px-Knolvoet_bij_bloemkool_%28Plasmodiophora_brassicae_on_cauliflower%29.jpg' },
  { nama: 'Bercak Ungu (Trotol)', kategori: 'Jamur', penyebab: 'Alternaria porri', tanaman: ['Bawang Merah', 'Bawang Putih', 'Bawang Daun'], ciriCiri: 'Bercak melekuk putih melebar jadi ungu/coklat, membentuk cincin kuning pucat di daun bawang.', kerugian: 'Daun patah atau kering, umbi tidak membesar (kerdil) dan cepat busuk di gudang.', penanganan: 'Semprot air sehabis hujan lebat malam hari. Fungisida Mankozeb, Klorotalonil, atau Iprodion.', sasaranPestisida: 'Bercak Ungu', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/60/Chain_of_conidia_of_an_Alternaria_sp._fungus_PHIL_3963_lores.jpg' },
  { nama: 'Embun Bulu (Downy Mildew)', kategori: 'Jamur', penyebab: 'Pseudoperonospora cubensis', tanaman: ['Mentimun', 'Melon', 'Semangka', 'Bawang Merah'], ciriCiri: 'Bercak kuning bersudut-sudut dibatasi tulang daun. Bagian bawah daun terdapat jamur beludru abu-abu/ungu.', kerugian: 'Daun mati mengering dengan sangat cepat, menurunkan gula buah.', penanganan: 'Fungisida Mankozeb, Propineb, Metiram, atau Dimetomorf.', sasaranPestisida: 'Embun Bulu', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Downy_Mildew_on_Grape_%2834316147496%29.jpg/960px-Downy_Mildew_on_Grape_%2834316147496%29.jpg' },
  { nama: 'Embun Tepung (Powdery Mildew)', kategori: 'Jamur', penyebab: 'Oidium sp.', tanaman: ['Melon', 'Semangka', 'Kacang', 'Apel', 'Mangga', 'Mentimun'], ciriCiri: 'Lapisan tepung putih menyelimuti permukaan atas dan bawah daun. Daun tua menguning rontok.', kerugian: 'Menghambat fotosintesis secara masif di cuaca kering.', penanganan: 'Fungisida belerang (Sulfur), Heksakonazol, atau Difenokonazol.', sasaranPestisida: 'Embun Tepung', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Oidium_tuckeri.jpg/960px-Oidium_tuckeri.jpg' },
  { nama: 'Karat Daun', kategori: 'Jamur', penyebab: 'Puccinia spp.', tanaman: ['Kacang', 'Kopi', 'Jagung Manis', 'Kangkung'], ciriCiri: 'Timbul bercak bintil-bintil seperti serbuk karat besi warna oranye, merah bata, atau coklat tua di bawah daun.', kerugian: 'Tanaman menggugurkan daun lebih awal, polong kacang tidak terisi.', penanganan: 'Fungisida Triazol (Propikonazol, Tebukonazol). Kurangi kelembapan kanopi.', sasaranPestisida: 'Karat Daun', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Wheat_leaf_rust.jpg/960px-Wheat_leaf_rust.jpg' },
  { nama: 'Rebah Semai (Damping Off)', kategori: 'Jamur', penyebab: 'Pythium spp. / Rhizoctonia solani', tanaman: ['Semua Tanaman (Persemaian)'], ciriCiri: 'Pangkal batang bibit yang baru semai tiba-tiba busuk kebasahan, menyempit, lalu bibit rebah (mati).', kerugian: 'Gagal pindah tanam, pembibitan hancur seketika.', penanganan: 'Jangan terlalu lembab/becek. Semprot/Kocor Fungisida Propamokarb atau Metalaksil.', sasaranPestisida: 'Rebah Semai', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Pythium_insidiosum.jpg/960px-Pythium_insidiosum.jpg' },
  { nama: 'Busuk Pangkal Batang', kategori: 'Jamur', penyebab: 'Phytophthora capsici', tanaman: ['Cabai', 'Tomat', 'Mentimun', 'Pepaya', 'Lada'], ciriCiri: 'Pangkal batang di atas tanah membusuk, berwarna hitam dan basah. Kulit terkelupas.', kerugian: 'Layunya seluruh tajuk tanaman.', penanganan: 'Oleskan pasta fungisida (Mankozeb/Tembaga) di luka batang. Kocor Dimetomorf.', sasaranPestisida: 'Busuk Batang', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Pythium_insidiosum.jpg/960px-Pythium_insidiosum.jpg' },
  { nama: 'Hawar Daun Jagung', kategori: 'Jamur', penyebab: 'Helminthosporium maydis / Bipolaris', tanaman: ['Jagung', 'Jagung Manis'], ciriCiri: 'Bercak daun berbentuk elips abu-abu coklat, menyatu membuat daun mengering seperti terbakar.', kerugian: 'Kerusakan tongkol atau penurunan bobot panen.', penanganan: 'Tanam varietas tahan, fungisida Mankozeb/Azoksistrobin.', sasaranPestisida: 'Hawar Daun', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/60/Chain_of_conidia_of_an_Alternaria_sp._fungus_PHIL_3963_lores.jpg' },
  { nama: 'Bulai Jagung', kategori: 'Jamur', penyebab: 'Peronosclerospora maydis', tanaman: ['Jagung', 'Jagung Manis'], ciriCiri: 'Daun klorotik (kuning pucat atau putih) bergaris memanjang searah tulang daun. Terdapat serbuk putih jamur.', kerugian: 'Bisa gagal panen total 100% jika menyerang tanaman muda.', penanganan: 'Perlakuan benih (Seed treatment) dengan Metalaksil atau Dimetomorf sebelum tanam.', sasaranPestisida: 'Bulai', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Downy_Mildew_on_Grape_%2834316147496%29.jpg/960px-Downy_Mildew_on_Grape_%2834316147496%29.jpg' },
  { nama: 'Karat Putih', kategori: 'Jamur', penyebab: 'Albugo candida', tanaman: ['Bayam', 'Kangkung', 'Sawi', 'Pakcoy'], ciriCiri: 'Terdapat bercak putih berbentuk melepuh / bisul / pustul di bagian bawah daun kangkung/bayam.', kerugian: 'Sayuran tidak laku dijual karena daun cacat/bolong.', penanganan: 'Fungisida Mankozeb atau Azoksistrobin. Perbaikan sirkulasi udara bedengan.', sasaranPestisida: 'Karat Putih', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Wheat_leaf_rust.jpg/960px-Wheat_leaf_rust.jpg' },
  { nama: 'Pucuk Pucat (Mboler)', kategori: 'Jamur', penyebab: 'Fusarium sp.', tanaman: ['Bawang Merah'], ciriCiri: 'Ujung daun menguning melintir (mboler), daun lemas rebah, umbi membusuk dan akar berwarna merah muda.', kerugian: 'Kematian massal, gagal panen, menular ke umbi tetangga.', penanganan: 'Fungisida Difenokonazol/Prokloraz. Kocor Tricoderma sejak awal tanam.', sasaranPestisida: 'Pucuk Pucat', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Fusarium_wilt_symptom_tobacco.jpg/960px-Fusarium_wilt_symptom_tobacco.jpg' },
  { nama: 'Jamur Upas', kategori: 'Jamur', penyebab: 'Corticium salmonicolor / Erythricium', tanaman: ['Jeruk', 'Kopi', 'Kakao', 'Karet'], ciriCiri: 'Lapisan miselium jamur menyerupai kerak kerak pink (salmon) pada cabang/batang berkayu. Ranting mati/kering.', kerugian: 'Matinya cabang produktif (dieback).', penanganan: 'Pangkas dan bakar cabang sakit, oles luka dengan bubur bordeaux (Tembaga Oksida/Sulfat).', sasaranPestisida: 'Jamur Upas', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Colletotrichum_lindemuthianum.jpg/960px-Colletotrichum_lindemuthianum.jpg' },
  { nama: 'Bercak Coklat', kategori: 'Jamur', penyebab: 'Alternaria solani', tanaman: ['Tomat', 'Kentang'], ciriCiri: 'Mirip trotol bawang tapi menyerang tomat/kentang. Bercak konsentris berlapis mirip target sasaran panah.', kerugian: 'Daun rontok dan buah bisa melepuh busuk hitam di pangkal.', penanganan: 'Rotasi tanaman, Fungisida Mankozeb/Klorotalonil.', sasaranPestisida: 'Bercak Coklat', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/60/Chain_of_conidia_of_an_Alternaria_sp._fungus_PHIL_3963_lores.jpg' },
  { nama: 'Bercak Cincin Pepaya', kategori: 'Jamur', penyebab: 'Phytophthora palmivora (atau Virus PRSV)', tanaman: ['Pepaya'], ciriCiri: 'Buah berbercak busuk berair atau bercak cincin (jika PRSV).', kerugian: 'Buah busuk di pohon atau cacat.', penanganan: 'Buang buah terinfeksi, Semprot Tembaga Hidroksida / Mankozeb.', sasaranPestisida: 'Busuk Buah', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Colletotrichum_lindemuthianum.jpg/960px-Colletotrichum_lindemuthianum.jpg' },
  { nama: 'Busuk Leher Akar (Lanas)', kategori: 'Jamur', penyebab: 'Phytophthora nicotianae', tanaman: ['Tembakau', 'Cabai', 'Tomat'], ciriCiri: 'Pangkal batang menghitam dan melesak, daun layu mendadak.', kerugian: 'Kerusakan sangat fatal.', penanganan: 'Aplikasi agen hayati Trichoderma di tanah, Metalaksil.', sasaranPestisida: 'Layu Fusarium', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Pythium_insidiosum.jpg/960px-Pythium_insidiosum.jpg' },
  { nama: 'Hawar Pelepah Padi', kategori: 'Jamur', penyebab: 'Rhizoctonia solani', tanaman: ['Padi'], ciriCiri: 'Bercak abu kehitaman besar dengan tepi coklat di pelepah daun padi dekat permukaan air.', kerugian: 'Batang roboh, gabah hampa karena asupan makanan ke malai terputus.', penanganan: 'Fungisida Heksakonazol atau Trisiklazol.', sasaranPestisida: 'Hawar Daun', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/60/Chain_of_conidia_of_an_Alternaria_sp._fungus_PHIL_3963_lores.jpg' },
  { nama: 'Blas Padi (Potong Leher)', kategori: 'Jamur', penyebab: 'Pyricularia oryzae', tanaman: ['Padi'], ciriCiri: 'Bercak belah ketupat di daun (Blas daun). Atau tangkai bulir (leher) membusuk patah sehingga malai putih hampa.', kerugian: 'Penurunan panen drastis, patah leher sangat mematikan hasil padi.', penanganan: 'Gunakan benih tahan, tidak menggunakan Urea (N) berlebih. Fungisida Trisiklazol atau Azoksistrobin.', sasaranPestisida: 'Blas Padi', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Wheat_leaf_rust.jpg/960px-Wheat_leaf_rust.jpg' },
  { nama: 'Layu Verticillium', kategori: 'Jamur', penyebab: 'Verticillium dahliae', tanaman: ['Cabai', 'Tomat', 'Terong', 'Kapas'], ciriCiri: 'Layu sepihak (sebagian cabang), daun menguning berbentuk V (V-shaped yellowing).', kerugian: 'Layunya perlahan, tanaman merana hingga mati lambat.', penanganan: 'Solarisasi tanah (menutup plastik mulsa di musim panas). Tidak mudah disembuhkan dengan kimia.', sasaranPestisida: 'Layu Fusarium', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Fusarium_wilt_symptom_tobacco.jpg/960px-Fusarium_wilt_symptom_tobacco.jpg' },
  { nama: 'Kanker Batang Karet/Kakao', kategori: 'Jamur', penyebab: 'Phytophthora palmivora', tanaman: ['Karet', 'Kakao', 'Jeruk'], ciriCiri: 'Kulit batang berbercak kemerahan/hitam dan mengeluarkan cairan/getah.', kerugian: 'Matinya pohon dewasa produktif.', penanganan: 'Kerok bagian kulit terserang dan oles dengan fungisida tembaga.', sasaranPestisida: 'Kanker Batang', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Colletotrichum_lindemuthianum.jpg/960px-Colletotrichum_lindemuthianum.jpg' },
  { nama: 'Busuk Pangkal Batang Sawit', kategori: 'Jamur', penyebab: 'Ganoderma boninense', tanaman: ['Kelapa Sawit'], ciriCiri: 'Pembusukan pada bagian bawah batang sawit (bonggol), muncul badan buah jamur berbentuk kipas keras. Pelepah layu dan patah menggantung.', kerugian: 'Hama penyakit utama perkebunan sawit, membunuh pohon sawit mature.', penanganan: 'Lubang tanam besar, rotasi dengan non-inang. Agen hayati Trichoderma spp.', sasaranPestisida: 'Busuk Batang', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Colletotrichum_lindemuthianum.jpg/960px-Colletotrichum_lindemuthianum.jpg' },
  { nama: 'Embun Jelaga', kategori: 'Jamur', penyebab: 'Capnodium spp. / Meliola spp.', tanaman: ['Mangga', 'Jeruk', 'Kopi', 'Kakao', 'Jambu'], ciriCiri: 'Permukaan atas daun/buah tertutup lapisan serbuk hitam seperti jelaga/arang tebal.', kerugian: 'Menghalangi sinar matahari untuk fotosintesis, walau tidak secara langsung merusak jaringan sel.', penanganan: 'Kendalikan hama Kutu Putih / Kutu Kebul (pembawa cairan embun madu penyebab jelaga). Semprot air sabun/minyak.', sasaranPestisida: 'Kutu Kebul', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Sooty_mold_on_Citrus.jpg/960px-Sooty_mold_on_Citrus.jpg' },

  // BAKTERI (10)
  { nama: 'Layu Bakteri', kategori: 'Bakteri', penyebab: 'Ralstonia solanacearum', tanaman: ['Cabai', 'Tomat', 'Kacang', 'Pisang', 'Terong'], ciriCiri: 'Layu mendadak dalam keadaan masih hijau. Keluar lendir/eksudat putih keruh dari batang yang direndam air bening.', kerugian: 'Sangat menular lewat air irigasi, tanaman layu mati dalam 1-3 hari.', penanganan: 'Bakterisida Tembaga Oksida, Kasugamisin, Streptomisin atau Agrept. Cabut dan musnahkan.', sasaranPestisida: 'Layu Bakteri', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Ralstonia_solanacearum_symptoms.jpg/960px-Ralstonia_solanacearum_symptoms.jpg' },
  { nama: 'Busuk Bakteri Erwinia (Lunak)', kategori: 'Bakteri', penyebab: 'Erwinia carotovora', tanaman: ['Kubis', 'Sawi', 'Bawang Merah', 'Kangkung', 'Selada', 'Lidah Buaya'], ciriCiri: 'Jaringan tanaman (daun/batang/krop) membusuk, menjadi sangat lunak, berlendir, dan berbau sangat busuk/menyengat kotoran.', kerugian: 'Sayuran membusuk di bedengan maupun rusak setelah panen (transportasi).', penanganan: 'Rotasi dengan tanaman bukan sayuran. Bakterisida Streptomisin/Tembaga/Asam Oksolinik.', sasaranPestisida: 'Busuk Bakteri', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Slime_flux_on_Camperdown_elm.png/960px-Slime_flux_on_Camperdown_elm.png' },
  { nama: 'Bercak Daun Bakteri (Xanthomonas)', kategori: 'Bakteri', penyebab: 'Xanthomonas campestris', tanaman: ['Tomat', 'Cabai', 'Kacang Panjang'], ciriCiri: 'Bercak kecil basah pada daun yang berkerak/kering kasar, dikelilingi halo (cincin) kuning terang.', kerugian: 'Daun gugur, kualias buah tomat cacat.', penanganan: 'Bakterisida Kasugamisin atau Tembaga Hidroksida.', sasaranPestisida: 'Bercak Bakteri', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Cercospora_beticola_on_sugar_beet.jpeg/960px-Cercospora_beticola_on_sugar_beet.jpeg' },
  { nama: 'Hawar Daun Bakteri (Kresek)', kategori: 'Bakteri', penyebab: 'Xanthomonas oryzae pv. oryzae', tanaman: ['Padi'], ciriCiri: 'Tepi daun padi menguning, kemudian mengering menjadi putih keabu-abuan. Terlihat ada butiran empulur (eksudat) pagi hari.', kerugian: 'Mati kerdil atau gabah hampa akibat kerusakan malai/daun bendera.', penanganan: 'Penggunaan varietas tahan (Inpari 32). Jarak tanam jajar legowo, Bakterisida Streptomisin atau Mankozeb Tembaga.', sasaranPestisida: 'Hawar Daun', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Cercospora_beticola_on_sugar_beet.jpeg/960px-Cercospora_beticola_on_sugar_beet.jpeg' },
  { nama: 'Kanker Bakteri Jeruk (Citrus Canker)', kategori: 'Bakteri', penyebab: 'Xanthomonas citri', tanaman: ['Jeruk', 'Nipis'], ciriCiri: 'Bercak gabus kasar menyembul pada daun, ranting, dan buah jeruk.', kerugian: 'Daun gugur, kualitas buah jelek dan cacat gabus ekspor ditolak.', penanganan: 'Pemangkasan bagian sakit, fungisida/bakterisida tembaga.', sasaranPestisida: 'Kanker Batang', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Cercospora_beticola_on_sugar_beet.jpeg/960px-Cercospora_beticola_on_sugar_beet.jpeg' },
  { nama: 'Busuk Hitam (Black Rot)', kategori: 'Bakteri', penyebab: 'Xanthomonas campestris pv. campestris', tanaman: ['Kubis', 'Sawi', 'Brokoli', 'Kembang Kol'], ciriCiri: 'Tepi daun kubis menguning membusuk dengan bentuk huruf V, tulang daun menghitam membusuk menjalar ke krop.', kerugian: 'Krop kubis busuk di dalam sebelum dipanen.', penanganan: 'Gunakan benih bebas patogen, perendaman air panas benih. Bakterisida Tembaga.', sasaranPestisida: 'Bercak Bakteri', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Slime_flux_on_Camperdown_elm.png/960px-Slime_flux_on_Camperdown_elm.png' },
  { nama: 'Penyakit Darah Pisang', kategori: 'Bakteri', penyebab: 'Blood Disease Bacterium (BDB)', tanaman: ['Pisang', 'Kepok'], ciriCiri: 'Daun kuning melayu (patah di pelepah). Jika batang/jantung pisang dipotong, keluar lendir bakteri berwarna merah kecoklatan.', kerugian: 'Buah pisang berlendir dan berdarah busuk, pohon mati menular.', penanganan: 'Musnahkan pohon sakit, sterilisasi parang/golok, potong jantung pisang setelah buah terakhir.', sasaranPestisida: 'Layu Bakteri', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Ralstonia_solanacearum_symptoms.jpg/960px-Ralstonia_solanacearum_symptoms.jpg' },
  { nama: 'Gusung Bulir Bakteri', kategori: 'Bakteri', penyebab: 'Burkholderia glumae', tanaman: ['Padi'], ciriCiri: 'Malai/gabah mengering tegak (hampa) berwarna kecoklatan/kelabu kusam, sedangkan daun tetap hijau.', kerugian: 'Penurunan panen gabah isi drastis.', penanganan: 'Bakterisida asam oksolinik.', sasaranPestisida: 'Bercak Bakteri', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Ralstonia_solanacearum_symptoms.jpg/960px-Ralstonia_solanacearum_symptoms.jpg' },
  { nama: 'Penyakit Kuning Jati (Bacterial Wilt)', kategori: 'Bakteri', penyebab: 'Pseudomonas spp.', tanaman: ['Tomat', 'Terong'], ciriCiri: 'Pembusukan dan nekrosis merata pada sumbu tangkai daun.', kerugian: 'Layu sepihak perlahan dan kerusakan sistem konduksi nutrisi.', penanganan: 'Fungisida & Bakterisida berbahan aktif Tembaga.', sasaranPestisida: 'Layu Bakteri', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Ralstonia_solanacearum_symptoms.jpg/960px-Ralstonia_solanacearum_symptoms.jpg' },
  { nama: 'Kudis Bakteri (Bacterial Scab)', kategori: 'Bakteri', penyebab: 'Streptomyces scabies', tanaman: ['Kentang', 'Umbi Umbian'], ciriCiri: 'Bercak kasar menonjol berkerak (seperti gabus) pada kulit umbi kentang.', kerugian: 'Nilai jual turun drastis (cacat fisik).', penanganan: 'Tanam benih bebas scab, hindari pemberian kapur berlebih karena patogen suka basa.', sasaranPestisida: 'Bercak Bakteri', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Ralstonia_solanacearum_symptoms.jpg/960px-Ralstonia_solanacearum_symptoms.jpg' },

  // VIRUS & LAINNYA (15)
  { nama: 'Virus Kuning (Geminivirus / BGMV)', kategori: 'Virus', penyebab: 'Begomovirus (Vektor: Kutu Kebul)', tanaman: ['Cabai', 'Tomat', 'Kacang Panjang', 'Mentimun', 'Melon'], ciriCiri: 'Daun muda menguning pucat terang pada tulang daun atau bercak kuning terang, daun keriting kerdil.', kerugian: 'Tidak ada buah yang terbentuk, kerusakan 100% jika terserang dini.', penanganan: 'Kendalikan vektor Kutu Kebul dengan Insektisida Imidakloprid, Pimetrozin, atau Abamektin. Cabut buang segera.', sasaranPestisida: 'Kutu Kebul', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Abutilon_pictum_serres_du_Luxembourg.jpg/960px-Abutilon_pictum_serres_du_Luxembourg.jpg' },
  { nama: 'Virus Mosaik (TMV/CMV)', kategori: 'Virus', penyebab: 'Tobacco/Cucumber Mosaic Virus (Vektor: Kutu Daun)', tanaman: ['Tembakau', 'Tomat', 'Cabai', 'Mentimun', 'Kacang'], ciriCiri: 'Daun belang-belang hijau terang dan gelap (mosaik), daun cacat menyempit mirip tali sepatu.', kerugian: 'Tanaman kerdil, buah cacat atau berbercak warna tidak merata.', penanganan: 'Bebaskan gulma inang, kendalikan Kutu Daun dengan Insektisida Abamektin/Tiametoksam.', sasaranPestisida: 'Kutu Daun', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Tomato_mosaic_virus_TMV_01.jpg/960px-Tomato_mosaic_virus_TMV_01.jpg' },
  { nama: 'Virus Keriting Bule (Chili Vein Banding)', kategori: 'Virus', penyebab: 'CVBV', tanaman: ['Cabai'], ciriCiri: 'Tulang daun menebal warna hijau gelap, daun melengkung ke atas, keriting kaku.', kerugian: 'Pucuk tidak berkembang.', penanganan: 'Basmi kutu thrips dan aphids.', sasaranPestisida: 'Thrips', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Tomato_mosaic_virus_TMV_01.jpg/960px-Tomato_mosaic_virus_TMV_01.jpg' },
  { nama: 'Penyakit Tungro', kategori: 'Virus', penyebab: 'Rice Tungro Virus (Vektor: Wereng Hijau)', tanaman: ['Padi'], ciriCiri: 'Tanaman kerdil, anakan sedikit, daun menguning jingga dari ujung menjalar ke pangkal.', kerugian: 'Sangat membahayakan persawahan, panen anjlok.', penanganan: 'Varietas tahan tungro, tanam serempak, kendalikan Wereng Hijau (Imidakloprid, BPMC).', sasaranPestisida: 'Wereng', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Tomato_mosaic_virus_TMV_01.jpg/960px-Tomato_mosaic_virus_TMV_01.jpg' },
  { nama: 'Bercak Cincin Kerdil (PRSV)', kategori: 'Virus', penyebab: 'Papaya Ringspot Virus', tanaman: ['Pepaya'], ciriCiri: 'Daun pucuk seperti tali sepatu (filiform), batang memiliki bercak hijau gelap berminyak, buah berbintik cincin/ring.', kerugian: 'Matikan produksi buah total.', penanganan: 'Kendalikan Kutu Daun, musnahkan pepaya sakit.', sasaranPestisida: 'Kutu Daun', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Tomato_mosaic_virus_TMV_01.jpg/960px-Tomato_mosaic_virus_TMV_01.jpg' },
  { nama: 'Penyakit Kerdil Rumput (Grassy Stunt)', kategori: 'Virus', penyebab: 'RGSV (Vektor: Wereng Coklat)', tanaman: ['Padi'], ciriCiri: 'Padi tumbuh kerdil lebat beranak banyak mirip rumput, daun sempit, kaku warna hijau kusam.', kerugian: 'Hampa total tidak berbunga/malai.', penanganan: 'Tanam padi tahan wereng coklat.', sasaranPestisida: 'Wereng', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Tomato_mosaic_virus_TMV_01.jpg/960px-Tomato_mosaic_virus_TMV_01.jpg' },
  { nama: 'Mosaik Belang Kacang Panjang', kategori: 'Virus', penyebab: 'Cowpea Aphid-Borne Mosaic Virus', tanaman: ['Kacang Panjang', 'Kedelai'], ciriCiri: 'Daun bercak-bercak hijau tua dan pucat, bentuk daun mengkerut tak wajar.', kerugian: 'Pertumbuhan lambat dan polong sangat pendek atau melengkung cacat.', penanganan: 'Pilih benih sehat tahan virus, semprot anti Kutu Daun.', sasaranPestisida: 'Kutu Daun', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Tomato_mosaic_virus_TMV_01.jpg/960px-Tomato_mosaic_virus_TMV_01.jpg' },
  { nama: 'Kerdil Pisang (Bunchy Top)', kategori: 'Virus', penyebab: 'Banana Bunchy Top Virus (Vektor: Kutu Daun Pentalonia)', tanaman: ['Pisang'], ciriCiri: 'Daun pisang pucuk mengecil, berdiri tegak menyatu membentuk roset/sapu (bunchy top). Tepi daun keriting/menguning.', kerugian: 'Pisang tidak akan pernah berbuah.', penanganan: 'Basmi pohon bersama bonggol akarnya, semprot kutu daun dengan Abamektin.', sasaranPestisida: 'Kutu Daun', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Tomato_mosaic_virus_TMV_01.jpg/960px-Tomato_mosaic_virus_TMV_01.jpg' },
  { nama: 'Nematoda Bintil Akar (Root-Knot)', kategori: 'Nematoda (Cacing)', penyebab: 'Meloidogyne spp.', tanaman: ['Tomat', 'Cabai', 'Kentang', 'Melon'], ciriCiri: 'Sering keliru dianggap penyakit layu. Akar membengkak tumor berbintil. Tanaman kerdil pucat layu kronis.', kerugian: 'Menggagalkan penyerapan pupuk dan air. Tanah terinfeksi lama.', penanganan: 'Rotasi dengan Bunga Kenikir (Marigold). Kocor dengan Nematisida Karbofuran atau Fluensulfon.', sasaranPestisida: 'Nematoda', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Root-knot_nematode.jpg/960px-Root-knot_nematode.jpg' },
  { nama: 'Busuk Pangkal (Phoma)', kategori: 'Jamur', penyebab: 'Phoma lingam', tanaman: ['Kubis', 'Sawi', 'Brokoli'], ciriCiri: 'Bercak abu-abu bulat dengan bintik-bintik hitam di dalamnya (piknidia). Pada pangkal batang terdapat kanker yang meluas menyebabkan rebah.', kerugian: 'Bisa merusak seluruh bedengan persemaian kubis.', penanganan: 'Benih bersertifikat bebas penyakit, fungisida Iprodion.', sasaranPestisida: 'Busuk Batang', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Pythium_insidiosum.jpg/960px-Pythium_insidiosum.jpg' }
];`;

let startIdx = content.indexOf('const PENYAKIT_CATALOG = [');
let endIdx = content.indexOf('];', startIdx) + 2;

content = content.substring(0, startIdx) + newData + content.substring(endIdx);

fs.writeFileSync('src/views/CariPenyakitView.tsx', content);
