const fs = require('fs');
let content = fs.readFileSync('src/views/CariPestisidaView.tsx', 'utf-8');

const newCatalog = `const PESTISIDA_CATALOG = [
  // INSEKTISIDA (20)
  { nama: 'Curacron 500EC', jenis: 'Insektisida', bahanAktif: 'Profenofos 500 g/l', sasaran: ['Ulat Grayak', 'Kutu Daun', 'Thrips', 'Ulat Penggerek Batang'], kemampuan: 'Bekerja sebagai racun kontak dan lambung. Memiliki efek translaminar yang dapat menembus jaringan daun.', kekurangan: 'Beresiko menimbulkan resistensi jika digunakan terus-menerus. Bau sangat menyengat.', harga: 'Rp 75.000 / 250ml', dosis: '1.5 - 2 ml / Liter air' },
  { nama: 'Demolish 18EC', jenis: 'Insektisida / Akarisida', bahanAktif: 'Abamektin 18 g/l', sasaran: ['Tungau', 'Thrips', 'Pengorok Daun', 'Kutu Daun'], kemampuan: 'Sangat efektif mengendalikan kutu-kutuan dan tungau penyebab keriting daun.', kekurangan: 'Tidak efektif untuk hama ulat besar. Dosis harus pas karena rawan overdosis yang membakar pupus.', harga: 'Rp 90.000 / 100ml', dosis: '0.5 - 1 ml / Liter air' },
  { nama: 'Regent 50SC', jenis: 'Insektisida', bahanAktif: 'Fipronil 50 g/l', sasaran: ['Semut', 'Rayap', 'Orong-orong', 'Kutu Kebul', 'Thrips'], kemampuan: 'Racun kontak dan lambung serta sistemik. Efektif mengendalikan hama tanah dan hama di permukaan daun.', kekurangan: 'Bekerja lambat, hama tidak langsung mati namun berhenti makan.', harga: 'Rp 80.000 / 250ml', dosis: '1 - 2 ml / Liter air' },
  { nama: 'Prevathon 50SC', jenis: 'Insektisida', bahanAktif: 'Klorantraniliprol 50 g/l', sasaran: ['Ulat Grayak', 'Ulat Penggerek Buah', 'Ulat Penggulung Daun'], kemampuan: 'Insektisida sistemik spesialis ulat. Melindungi tanaman hingga ke tunas baru. Aman bagi musuh alami.', kekurangan: 'Harga sangat mahal. Tidak efektif untuk hama kutu-kutuan.', harga: 'Rp 140.000 / 100ml', dosis: '1.5 - 2 ml / Liter air' },
  { nama: 'Bamex 18EC', jenis: 'Insektisida', bahanAktif: 'Abamektin 18 g/l', sasaran: ['Kutu Daun', 'Thrips', 'Tungau'], kemampuan: 'Racun kontak kuat membasmi hama penyebab keriting daun.', kekurangan: 'Tidak spesifik untuk ulat besar.', harga: 'Rp 85.000 / 100ml', dosis: '0.5 - 1 ml / Liter air' },
  { nama: 'Alika 247ZC', jenis: 'Insektisida', bahanAktif: 'Lamda sihalotrin 106 g/l, Tiametoksam 141 g/l', sasaran: ['Kutu Kebul', 'Wereng', 'Kepik', 'Walang Sangit', 'Ulat'], kemampuan: 'Kombinasi 2 bahan aktif kontak dan sistemik. Mempunyai efek knock-down cepat dan perlindungan lama.', kekurangan: 'Harga relatif mahal.', harga: 'Rp 120.000 / 100ml', dosis: '0.5 - 1 ml / Liter air' },
  { nama: 'Decis 25EC', jenis: 'Insektisida', bahanAktif: 'Deltametrin 25 g/l', sasaran: ['Ulat Api', 'Ulat Grayak', 'Lalat Buah', 'Kepik'], kemampuan: 'Racun kontak dan lambung berspektrum luas. Efek melumpuhkan serangga sangat cepat (knock down).', kekurangan: 'Tidak sistemik, tidak bisa menjangkau hama yang sembunyi di dalam daun/batang.', harga: 'Rp 65.000 / 250ml', dosis: '1 - 2 ml / Liter air' },
  { nama: 'Confidor 200SL', jenis: 'Insektisida', bahanAktif: 'Imidakloprid 200 g/l', sasaran: ['Wereng', 'Kutu Daun (Aphids)', 'Kutu Kebul', 'Thrips'], kemampuan: 'Sangat sistemik, terserap akar dan daun. Ampuh membasmi serangga penusuk-penghisap pembawa virus kuning.', kekurangan: 'Penggunaan terus menerus tanpa rolling cepat menimbulkan resistensi Kutu Kebul.', harga: 'Rp 100.000 / 100ml', dosis: '1 ml / Liter air' },
  { nama: 'Sivanto Prime', jenis: 'Insektisida', bahanAktif: 'Flupiradifuron 200 g/l', sasaran: ['Kutu Kebul', 'Kutu Daun', 'Wereng'], kemampuan: 'Bekerja cepat menghentikan hisapan hama (fast feeding cessation). Aman untuk serangga penyerbuk (lebah).', kekurangan: 'Harga mahal, spesifik hanya untuk hama penghisap.', harga: 'Rp 180.000 / 100ml', dosis: '1 - 1.5 ml / Liter air' },
  { nama: 'Pegasus 500SC', jenis: 'Insektisida / Akarisida', bahanAktif: 'Diafentiuron 500 g/l', sasaran: ['Tungau', 'Thrips', 'Kutu Kebul', 'Kutu Daun'], kemampuan: 'Bekerja melumpuhkan pernafasan hama (translaminar). Efek daun menjadi lebih hijau (phytotonic).', kekurangan: 'Hama tidak langsung mati seketika (mati perlahan 2-3 hari).', harga: 'Rp 115.000 / 250ml', dosis: '1 - 2 ml / Liter air' },
  { nama: 'Vayego 200SC', jenis: 'Insektisida', bahanAktif: 'Tetraniliprol 200 g/l', sasaran: ['Ulat Grayak', 'Ulat Penggerek', 'Spodoptera'], kemampuan: 'Spesialis ulat tingkat dewa, sangat kuat dan sistemik tahan lama.', kekurangan: 'Harga sangat mahal.', harga: 'Rp 195.000 / 50ml', dosis: '0.5 - 1 ml / Liter air' },
  { nama: 'Dursban 200EC', jenis: 'Insektisida', bahanAktif: 'Klorpirifos 200 g/l', sasaran: ['Semut', 'Rayap', 'Ulat Tanah', 'Ulat Grayak'], kemampuan: 'Racun kontak, lambung dan pernafasan (gas). Ampuh untuk hama yang bersembunyi di dalam tanah.', kekurangan: 'Bau sangat menyengat, sangat beracun (golongan organofosfat merah).', harga: 'Rp 65.000 / 500ml', dosis: '2 ml / Liter air' },
  { nama: 'Winder 100EC', jenis: 'Insektisida', bahanAktif: 'Imidakloprid 100 g/l', sasaran: ['Kutu Daun', 'Kutu Kebul', 'Wereng'], kemampuan: 'Sistemik dan lambung untuk hama penghisap daun.', kekurangan: 'Dosis perlu disesuaikan di musim hujan karena mudah tercuci.', harga: 'Rp 75.000 / 250ml', dosis: '1.5 ml / Liter air' },
  { nama: 'Spontan 400SL', jenis: 'Insektisida', bahanAktif: 'Dimehipo 400 g/l', sasaran: ['Penggerek Batang (Sundep/Beluk)', 'Wereng Coklat', 'Lalat Daun'], kemampuan: 'Sangat sistemik terserap ke seluruh jaringan tanaman.', kekurangan: 'Racun sangat kuat, berbahaya jika tidak memakai pelindung.', harga: 'Rp 50.000 / 500ml', dosis: '1.5 - 2 ml / Liter air' },
  { nama: 'Trigard 75WP', jenis: 'Insektisida', bahanAktif: 'Siromazin 75%', sasaran: ['Lalat Pengorok Daun (Liriomyza)'], kemampuan: 'Insektisida pengatur tumbuh serangga (IGR), mencegah telur menetas dan larva ganti kulit.', kekurangan: 'Sangat spesifik hanya untuk lalat pengorok daun.', harga: 'Rp 80.000 / 15gr', dosis: '1 gr / Liter air' },
  { nama: 'AgriMec 18EC', jenis: 'Insektisida', bahanAktif: 'Abamektin 18 g/l', sasaran: ['Tungau', 'Thrips'], kemampuan: 'Sangat ampuh membasmi tungau penyebab daun melengkung ke bawah.', kekurangan: 'Awas overdosis menyebabkan daun menguning.', harga: 'Rp 110.000 / 100ml', dosis: '0.5 ml / Liter air' },
  { nama: 'Samite 135EC', jenis: 'Akarisida', bahanAktif: 'Piridaben 135 g/l', sasaran: ['Tungau Kuning', 'Tungau Merah'], kemampuan: 'Akarisida kontak kuat, membunuh tungau dalam hitungan menit.', kekurangan: 'Hanya membunuh tungau, tidak membunuh thrips atau kutu kebul.', harga: 'Rp 80.000 / 100ml', dosis: '1 ml / Liter air' },
  { nama: 'Movento Energy', jenis: 'Insektisida', bahanAktif: 'Spirotetramat 120 g/l, Imidakloprid 120 g/l', sasaran: ['Kutu Kebul', 'Kutu Daun', 'Kutu Putih'], kemampuan: 'Sistemik dua arah (xilem dan floem), membunuh hama dari daun hingga akar.', kekurangan: 'Harga sangat mahal.', harga: 'Rp 200.000 / 100ml', dosis: '1 - 1.5 ml / Liter air' },
  { nama: 'Matador 25EC', jenis: 'Insektisida', bahanAktif: 'Lamda sihalotrin 25 g/l', sasaran: ['Ulat Grayak', 'Kepik', 'Walang Sangit'], kemampuan: 'Daya basmi cepat dengan efek racun kontak yang kuat.', kekurangan: 'Tidak sistemik.', harga: 'Rp 55.000 / 250ml', dosis: '1.5 ml / Liter air' },
  { nama: 'Starkle 20SG', jenis: 'Insektisida', bahanAktif: 'Dinotefuran 20%', sasaran: ['Kutu Kebul', 'Wereng', 'Thrips'], kemampuan: 'Racun lambung dan kontak sistemik kuat, mudah larut, tidak menyumbat spuyer.', kekurangan: 'Mahal untuk skala besar.', harga: 'Rp 75.000 / 100gr', dosis: '1 gr / Liter air' },

  // FUNGISIDA (20)
  { nama: 'Antracol 70WP', jenis: 'Fungisida', bahanAktif: 'Propineb 70%', sasaran: ['Antraknosa (Patek)', 'Bercak Daun', 'Busuk Daun', 'Rebah Semai'], kemampuan: 'Fungisida kontak preventif (pencegahan) dengan tambahan zinc (ZPT) yang membuat daun lebih hijau.', kekurangan: 'Mudah tercuci air hujan jika tidak ditambah perekat. Bentuk tepung menyumbat spuyer jika tidak diaduk rata.', harga: 'Rp 95.000 / 500gr', dosis: '2 - 3 gr / Liter air' },
  { nama: 'Amistar Top 325SC', jenis: 'Fungisida', bahanAktif: 'Azoksistrobin 200 g/l, Difenokonazol 125 g/l', sasaran: ['Antraknosa (Patek)', 'Bercak Ungu', 'Bercak Daun', 'Busuk Batang', 'Busuk Daun'], kemampuan: 'Fungisida sistemik kuratif (pengobatan) spektrum sangat luas. Mengendalikan penyakit hampir di semua fase tanaman.', kekurangan: 'Harga sangat mahal. Pemakaian overdosis saat berbunga dapat menyebabkan bunga rontok / kaku.', harga: 'Rp 145.000 / 100ml', dosis: '0.5 - 1 ml / Liter air' },
  { nama: 'Bion M 1/48WP', jenis: 'Fungisida', bahanAktif: 'Asibenzolar-S-metil 1%, Mankozeb 48%', sasaran: ['Busuk Buah', 'Patek', 'Busuk Daun Phytophthora'], kemampuan: 'Mengaktifkan sistem pertahanan (imun) alami tanaman sebelum terserang penyakit.', kekurangan: 'Fungsinya lebih kuat ke pencegahan daripada penyembuhan instan.', harga: 'Rp 120.000 / 500gr', dosis: '2 - 3 gr / Liter air' },
  { nama: 'Dithane M-45 80WP', jenis: 'Fungisida', bahanAktif: 'Mankozeb 80%', sasaran: ['Patek', 'Bercak Daun', 'Busuk Daun', 'Embun Bulu'], kemampuan: 'Fungisida kontak berspektrum sangat luas, merupakan andalan pencegahan di musim hujan.', kekurangan: 'Meninggalkan residu lapisan kuning pada daun. Beresiko menggumpal saat dilarutkan.', harga: 'Rp 110.000 / 1kg', dosis: '2 - 3 gr / Liter air' },
  { nama: 'Score 250EC', jenis: 'Fungisida', bahanAktif: 'Difenokonazol 250 g/l', sasaran: ['Bercak Daun Cercospora', 'Patek', 'Bercak Ungu Trotol'], kemampuan: 'Fungisida sistemik pengobatan yang sangat kuat. Membuat bobot buah/umbi meningkat.', kekurangan: 'Cairan kental agak pekat, harga premium.', harga: 'Rp 135.000 / 250ml', dosis: '0.5 - 1 ml / Liter air' },
  { nama: 'Nativo 75WG', jenis: 'Fungisida', bahanAktif: 'Tebukonazol 50%, Trifloksistrobin 25%', sasaran: ['Bercak Daun', 'Patek', 'Embun Tepung'], kemampuan: 'Fungisida mesostemik dan sistemik. Melindungi daun luar dan dalam sangat lama.', kekurangan: 'Harga sangat mahal per gram.', harga: 'Rp 85.000 / 50gr', dosis: '0.5 - 1 gr / Liter air' },
  { nama: 'Revus 250SC', jenis: 'Fungisida', bahanAktif: 'Mandipropamid 250 g/l', sasaran: ['Busuk Daun Phytophthora', 'Embun Bulu'], kemampuan: 'Sangat spesialis untuk busuk daun tomat/kentang, tahan cucian air hujan (lokosistemik).', kekurangan: 'Hanya efektif untuk kelompok Oomycetes (busuk daun basah).', harga: 'Rp 130.000 / 100ml', dosis: '1 - 2 ml / Liter air' },
  { nama: 'Topsin-M 70WP', jenis: 'Fungisida', bahanAktif: 'Tiofanat Metil 70%', sasaran: ['Layu Fusarium', 'Patek', 'Embun Tepung'], kemampuan: 'Sistemik kuat untuk mengatasi layu jamur dan infeksi pembuluh batang.', kekurangan: 'Sering dipakai terus-menerus sehingga rawan resistensi jamur.', harga: 'Rp 75.000 / 500gr', dosis: '1.5 - 2 gr / Liter air' },
  { nama: 'Cabrio 250EC', jenis: 'Fungisida', bahanAktif: 'Piraklostrobin 250 g/l', sasaran: ['Patek', 'Bercak Daun', 'Layu Daun'], kemampuan: 'Memberikan efek hijau mengkilap (greening effect) selain membunuh jamur.', kekurangan: 'Pemakaian berlebih menyebabkan daun agak kaku.', harga: 'Rp 140.000 / 250ml', dosis: '1 ml / Liter air' },
  { nama: 'Rovral 50WP', jenis: 'Fungisida', bahanAktif: 'Iprodion 50%', sasaran: ['Bercak Ungu Bawang Merah (Trotol)', 'Busuk Sclerotinia'], kemampuan: 'Sangat efektif menyembuhkan trotol pada bawang merah dan busuk leher.', kekurangan: 'Bentuk powder harus teliti dalam pelarutan.', harga: 'Rp 120.000 / 100gr', dosis: '1.5 - 2 gr / Liter air' },
  { nama: 'Nativo 75WG', jenis: 'Fungisida', bahanAktif: 'Trifloksistrobin 25%, Tebukonazol 50%', sasaran: ['Antraknosa (Patek)', 'Bercak Daun', 'Embun Tepung'], kemampuan: 'Sistemik dan mesostemik yang tahan lama mencegah patek.', kekurangan: 'Sangat mahal per sachet.', harga: 'Rp 35.000 / 12.5gr', dosis: '0.5 gr / Liter air' },
  { nama: 'Taft 75WP', jenis: 'Fungisida', bahanAktif: 'Karbendazim 75%', sasaran: ['Layu Fusarium', 'Akar Gada'], kemampuan: 'Membasmi jamur akar jika dikocorkan ke tanah.', kekurangan: 'Kurang cocok untuk semprot daun.', harga: 'Rp 50.000 / 100gr', dosis: '2 gr / Liter air' },
  { nama: 'Detac 50WP', jenis: 'Fungisida', bahanAktif: 'Mankozeb 50%', sasaran: ['Busuk Daun', 'Patek'], kemampuan: 'Fungisida kontak murah dan terjangkau untuk skala luas.', kekurangan: 'Perlu mix dengan sistemik bila serangan parah.', harga: 'Rp 80.000 / 1kg', dosis: '3 gr / Liter air' },
  { nama: 'Folicur 430SC', jenis: 'Fungisida', bahanAktif: 'Tebukonazol 430 g/l', sasaran: ['Bercak Daun', 'Busuk Batang'], kemampuan: 'Punya efek ZPT yang menghambat pemanjangan ruas (tanaman jadi kokoh).', kekurangan: 'Jangan semprot saat fase pembungaan rawan gosong.', harga: 'Rp 90.000 / 100ml', dosis: '1 ml / Liter air' },
  { nama: 'Explore 250EC', jenis: 'Fungisida', bahanAktif: 'Difenokonazol 250 g/l', sasaran: ['Patek', 'Bercak Ungu'], kemampuan: 'Alternatif murah dari Score, efek mengkilapkan buah cabai.', kekurangan: 'Daya tahan sistemik agak pendek.', harga: 'Rp 85.000 / 250ml', dosis: '1 ml / Liter air' },
  { nama: 'Mancozeb Biru', jenis: 'Fungisida', bahanAktif: 'Mankozeb 80%', sasaran: ['Patek', 'Busuk Daun'], kemampuan: 'Fungisida pelindung luar berwarna biru, jamur tidak berani hinggap.', kekurangan: 'Bekas biru menempel di buah, harus dicuci sebelum dijual.', harga: 'Rp 95.000 / 1kg', dosis: '2 - 3 gr / Liter air' },
  { nama: 'Previcur N', jenis: 'Fungisida', bahanAktif: 'Propamokarb Hidroklorida 722 g/l', sasaran: ['Busuk Akar', 'Rebah Semai (Damping Off)'], kemampuan: 'Sistemik pencegah busuk akar dan pangkal batang.', kekurangan: 'Lebih efektif dikocor daripada disemprot.', harga: 'Rp 115.000 / 100ml', dosis: '2 ml / Liter air' },
  { nama: 'Infinito 68,75SC', jenis: 'Fungisida', bahanAktif: 'Fluopikolid 62.5 g/l, Propamokarb 625 g/l', sasaran: ['Busuk Daun (Phytophthora)', 'Embun Bulu'], kemampuan: 'Translaminar, penetrasi ke bawah daun, spesialis musim hujan parah.', kekurangan: 'Harga sangat mahal.', harga: 'Rp 150.000 / 100ml', dosis: '1.5 ml / Liter air' },
  { nama: 'Bendas 50WP', jenis: 'Fungisida', bahanAktif: 'Karbendazim 50%', sasaran: ['Antraknosa', 'Busuk Buah'], kemampuan: 'Obat patek sistemik yang sudah melegenda.', kekurangan: 'Perlu rolling agar tidak resisten.', harga: 'Rp 50.000 / 100gr', dosis: '1.5 gr / Liter air' },
  { nama: 'Ridomil Gold 68WG', jenis: 'Fungisida', bahanAktif: 'Mefenoksam 4%, Mankozeb 64%', sasaran: ['Busuk Daun Phytophthora', 'Layu Jamur'], kemampuan: 'Dua bahan aktif kuat menembus ke dalam jaringan untuk membunuh Oomycetes.', kekurangan: 'Hati-hati keracunan tanaman jika dosis berlebih.', harga: 'Rp 75.000 / 100gr', dosis: '2 - 3 gr / Liter air' },

  // BAKTERISIDA & LAINNYA (10)
  { nama: 'Agrept 20WP', jenis: 'Bakterisida', bahanAktif: 'Streptomisin sulfat 20%', sasaran: ['Layu Bakteri', 'Busuk Batang Bakteri', 'Busuk Lunak Erwinia'], kemampuan: 'Antibiotik pertanian sistemik. Efektif menghentikan layu bakteri pada tomat, cabai, kubis.', kekurangan: 'Bisa meracuni tanah jika digunakan berlebihan secara terus-menerus (merusak mikroba baik).', harga: 'Rp 45.000 / 50gr', dosis: '1.5 - 2 gr / Liter air' },
  { nama: 'Kuproxat 345SC', jenis: 'Bakterisida / Fungisida', bahanAktif: 'Tembaga Oksi Sulfat 345 g/l', sasaran: ['Bercak Daun Bakteri', 'Busuk Batang (Erwinia)', 'Patek'], kemampuan: 'Partikel tembaga cair berukuran nano. Merekat kuat dan membunuh bakteri/jamur secara serentak.', kekurangan: 'Jangan dicampur (mix) dengan pupuk daun atau pestisida ber-pH asam, akan menggumpal/rusak.', harga: 'Rp 65.000 / 200ml', dosis: '2 ml / Liter air' },
  { nama: 'Nordox 56WP', jenis: 'Bakterisida / Fungisida', bahanAktif: 'Tembaga Oksida 56%', sasaran: ['Busuk Buah', 'Busuk Bakteri', 'Cacar Daun'], kemampuan: 'Pelindung kontak (protectant) berbasis tembaga bubuk merah bata.', kekurangan: 'Bentuk butiran sangat padat, keras larut bila tidak dikocok kuat. Rawan membakar pupus muda.', harga: 'Rp 60.000 / 100gr', dosis: '1 - 2 gr / Liter air' },
  { nama: 'Bactocyn 150AL', jenis: 'Bakterisida', bahanAktif: 'Oksitetrasiklin 150 g/l', sasaran: ['Layu Bakteri (Ralstonia)'], kemampuan: 'Antibiotik cair yang mudah diserap jaringan xilem tanaman.', kekurangan: 'Tidak boleh dicampur produk kalsium tinggi.', harga: 'Rp 50.000 / 100ml', dosis: '1.5 ml / Liter air' },
  { nama: 'Plantomycin 7SP', jenis: 'Bakterisida', bahanAktif: 'Streptomisin 7%', sasaran: ['Layu Bakteri'], kemampuan: 'Menghentikan penyebaran bakteri lewat jaringan air tanaman.', kekurangan: 'Harus segera diaplikasikan di gejala awal layu.', harga: 'Rp 40.000 / 100gr', dosis: '1.5 gr / Liter air' },
  { nama: 'Fungitox 70WP', jenis: 'Moluskisida', bahanAktif: 'Metaldehida 70%', sasaran: ['Siput', 'Keong Mas'], kemampuan: 'Racun lambung berbentuk tepung untuk disemprot ke sarang siput daun.', kekurangan: 'Bahaya tertelan hewan peliharaan.', harga: 'Rp 35.000 / 100gr', dosis: '2 gr / Liter air' },
  { nama: 'Toxiput 5G', jenis: 'Moluskisida', bahanAktif: 'Metaldehida 5%', sasaran: ['Siput Darat', 'Lintah Bulan'], kemampuan: 'Racun tabur/umpan. Sangat ampuh menarik siput dan membunuhnya di tempat.', kekurangan: 'Hancur jika terkena hujan lebat terus menerus.', harga: 'Rp 45.000 / 250gr', dosis: 'Taburkan merata di bedengan' },
  { nama: 'Spreader/Sticker (Spur)', jenis: 'Perekat / Perata', bahanAktif: 'Alkil Poliglikol Eter', sasaran: ['Semua jenis hama/penyakit'], kemampuan: 'Bukan pestisida, tapi Wajib dipakai saat musim hujan agar racun tidak luntur.', kekurangan: '-', harga: 'Rp 35.000 / 500ml', dosis: '0.5 - 1 ml / Liter air' },
  { nama: 'Furadan 3GR', jenis: 'Nematisida / Insektisida', bahanAktif: 'Karbofuran 3%', sasaran: ['Nematoda Bintil Akar', 'Ulat Tanah', 'Orong-orong'], kemampuan: 'Racun tabur tanah ungu, sangat mematikan serangga tanah.', kekurangan: 'Zat aktif akan dilarang karena sangat beracun bagi manusia dan burung (residu tinggi).', harga: 'Rp 25.000 / 1kg', dosis: 'Tabur 5-10 gr per lubang tanam' },
  { nama: 'Petrogenol 800L', jenis: 'Atraktan', bahanAktif: 'Metil Eugenol 800 g/l', sasaran: ['Lalat Buah Jantan'], kemampuan: 'Cairan pemikat lalat buah jantan, digunakan bersama perangkap botol bekas.', kekurangan: 'Tidak membunuh lalat betina, hanya mengurangi populasi pejantan kawin.', harga: 'Rp 15.000 / 5ml', dosis: 'Diteteskan di kapas dalam botol' }
];`

const startIndex = content.indexOf('const PESTISIDA_CATALOG = [');
const endIndex = content.indexOf('];', startIndex) + 2;

content = content.substring(0, startIndex) + newCatalog + content.substring(endIndex);

fs.writeFileSync('src/views/CariPestisidaView.tsx', content);
