const fs = require('fs');
let content = fs.readFileSync('src/views/CariPenyakitView.tsx', 'utf-8');

// Notice that PENYAKIT_CATALOG and PENYAKIT_OPTIONS are paired. Let's rebuild both.
const newOptions = `const PENYAKIT_OPTIONS = [
  { value: 'Patek', label: 'Antraknosa (Patek)' },
  { value: 'Layu Fusarium', label: 'Layu Fusarium' },
  { value: 'Layu Bakteri', label: 'Layu Bakteri' },
  { value: 'Bercak Daun', label: 'Bercak Daun Cercospora' },
  { value: 'Busuk Daun', label: 'Busuk Daun Phytophthora' },
  { value: 'Virus Kuning', label: 'Virus Kuning (Gemini Virus)' },
  { value: 'Akar Gada', label: 'Akar Gada (Clubroot)' },
  { value: 'Bercak Ungu', label: 'Bercak Ungu (Trotol)' },
  { value: 'Busuk Bakteri', label: 'Busuk Bakteri (Erwinia)' },
  { value: 'Embun Bulu', label: 'Embun Bulu (Downy Mildew)' },
  { value: 'Embun Tepung', label: 'Embun Tepung (Powdery Mildew)' },
  { value: 'Karat Daun', label: 'Karat Daun' },
  { value: 'Mosaik Virus', label: 'Mosaik Virus (TMV/CMV)' },
  { value: 'Busuk Pangkal Batang', label: 'Busuk Pangkal Batang (Phytophthora/Rhizoctonia)' },
  { value: 'Rebah Semai', label: 'Rebah Semai (Damping Off)' },
  { value: 'Bercak Bakteri', label: 'Bercak Bakteri (Xanthomonas)' },
  { value: 'Pucuk Pucat', label: 'Mboler / Pucuk Pucat (Bawang)' },
  { value: 'Mati Pucuk', label: 'Mati Pucuk (Dieback)' },
  { value: 'Kudis Buah', label: 'Kudis (Scab)' },
  { value: 'Layu Verticillium', label: 'Layu Verticillium' },
  { value: 'Bercak Coklat', label: 'Bercak Coklat (Alternaria solani)' },
  { value: 'Busuk Leher Akar', label: 'Busuk Leher Akar (Sclerotium)' },
  { value: 'Lalat Buah', label: 'Serangan Lalat Buah (Bactrocera)' },
  { value: 'Keriting Daun', label: 'Keriting Daun (Kutu/Thrips)' },
  { value: 'Puruh Akar', label: 'Nematoda Puruh Akar (Meloidogyne)' }
];`;

const newCatalog = `const PENYAKIT_CATALOG = [
  // 1-10
  { nama: 'Antraknosa (Patek)', kategori: 'Jamur', penyebab: 'Colletotrichum capsici', tanaman: ['Cabai', 'Tomat', 'Kacang'], ciriCiri: 'Bercak melingkar cekung hitam pada buah. Buah mengerut dan busuk.', kerugian: 'Gagal panen hingga 80%, penyebaran cepat di musim hujan.', penanganan: 'Fungisida Propineb/Mankozeb. Kumpulkan buah terinfeksi.', sasaranPestisida: 'Antraknosa (Patek)', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/77/Colletotrichum_lindemuthianum.jpg' },
  { nama: 'Layu Fusarium', kategori: 'Jamur', penyebab: 'Fusarium oxysporum', tanaman: ['Cabai', 'Tomat', 'Mentimun', 'Bawang Merah'], ciriCiri: 'Layu siang hari, segar pagi hari. Daun menguning bawah ke atas, vaskular coklat.', kerugian: 'Tanaman mati permanen, jamur bertahan puluhan tahun di tanah.', penanganan: 'Agen hayati Trichoderma. Fungisida Difenokonazol/Tebukonazol kocor.', sasaranPestisida: 'Layu Fusarium', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Fusarium_wilt_symptom_tobacco.jpg/960px-Fusarium_wilt_symptom_tobacco.jpg' },
  { nama: 'Layu Bakteri', kategori: 'Bakteri', penyebab: 'Ralstonia solanacearum', tanaman: ['Cabai', 'Tomat', 'Kacang'], ciriCiri: 'Layu mendadak hijau. Keluar eksudat lendir putih keruh dari batang yang dipotong.', kerugian: 'Mematikan mendadak, sangat menular lewat air.', penanganan: 'Bakterisida Tembaga Oksida atau Agrept. Cabut tanaman sakit.', sasaranPestisida: 'Layu Bakteri', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Ralstonia_solanacearum_symptoms.jpg/960px-Ralstonia_solanacearum_symptoms.jpg' },
  { nama: 'Bercak Daun Cercospora', kategori: 'Jamur', penyebab: 'Cercospora capsici', tanaman: ['Cabai', 'Tomat', 'Kacang', 'Kangkung'], ciriCiri: 'Bercak bulat mata katak (tengah abu, tepi coklat) di daun.', kerugian: 'Daun rontok (defoliasi), buah kecil, hasil menurun.', penanganan: 'Semprot Fungisida Mankozeb atau Azoksistrobin.', sasaranPestisida: 'Bercak Daun', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Cercospora_beticola_on_sugar_beet.jpeg/960px-Cercospora_beticola_on_sugar_beet.jpeg' },
  { nama: 'Busuk Daun Phytophthora', kategori: 'Jamur', penyebab: 'Phytophthora infestans', tanaman: ['Tomat', 'Cabai', 'Mentimun'], ciriCiri: 'Bercak hawar basah cepat membesar, hitam. Jamur putih di bawah daun.', kerugian: 'Menghancurkan seluruh kebun dalam hitungan hari (musim hujan/dingin).', penanganan: 'Fungisida sistemik Dimetomorf atau Mankozeb. Perbaiki drainase.', sasaranPestisida: 'Busuk Daun Phytophthora', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Late_blight_on_potato_leaf_2.jpg/960px-Late_blight_on_potato_leaf_2.jpg' },
  { nama: 'Virus Kuning (Gemini Virus)', kategori: 'Virus', penyebab: 'Begomovirus (vektor Kutu Kebul)', tanaman: ['Cabai', 'Tomat', 'Kacang'], ciriCiri: 'Tulang daun kuning terang, daun mengeriting, tanaman kerdil.', kerugian: 'Tanaman kerdil, tidak berbuah. Tidak ada obat sembuh total.', penanganan: 'Kendalikan vektor Kutu Kebul (Insektisida Imidakloprid, Abamektin). Cabut tanaman sakit.', sasaranPestisida: 'Kutu Kebul', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Abutilon_pictum_serres_du_Luxembourg.jpg/960px-Abutilon_pictum_serres_du_Luxembourg.jpg' },
  { nama: 'Akar Gada (Clubroot)', kategori: 'Jamur', penyebab: 'Plasmodiophora brassicae', tanaman: ['Kubis'], ciriCiri: 'Akar bengkak seperti gada, daun pucat layu siang hari.', kerugian: 'Akar rusak total tidak menyerap hara, gagal panen.', penanganan: 'Naikkan pH tanah (dolomit). Rotasi tanaman. Fungisida Flusulfamida.', sasaranPestisida: 'Akar Gada', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Knolvoet_bij_bloemkool_%28Plasmodiophora_brassicae_on_cauliflower%29.jpg/960px-Knolvoet_bij_bloemkool_%28Plasmodiophora_brassicae_on_cauliflower%29.jpg' },
  { nama: 'Bercak Ungu (Trotol)', kategori: 'Jamur', penyebab: 'Alternaria porri', tanaman: ['Bawang Merah'], ciriCiri: 'Bercak melekuk putih melebar jadi ungu, cincin kuning di daun bawang.', kerugian: 'Daun patah/kering, umbi tidak membesar (kerdil).', penanganan: 'Semprot air sehabis hujan. Fungisida Mankozeb / Iprodion.', sasaranPestisida: 'Bercak Ungu', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/60/Chain_of_conidia_of_an_Alternaria_sp._fungus_PHIL_3963_lores.jpg' },
  { nama: 'Busuk Bakteri (Erwinia)', kategori: 'Bakteri', penyebab: 'Erwinia carotovora', tanaman: ['Kubis', 'Bawang Merah', 'Kangkung'], ciriCiri: 'Sayur membusuk, berlendir, lunak, bau sangat menyengat.', kerugian: 'Hancur di lahan dan di gudang penyimpanan (panen).', penanganan: 'Bakterisida Streptomisin/Tembaga Oksida. Perbaiki sirkulasi udara.', sasaranPestisida: 'Busuk Lunak Erwinia', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Slime_flux_on_Camperdown_elm.png/960px-Slime_flux_on_Camperdown_elm.png' },
  { nama: 'Embun Bulu (Downy Mildew)', kategori: 'Jamur', penyebab: 'Pseudoperonospora cubensis', tanaman: ['Mentimun'], ciriCiri: 'Bercak kuning bersudut (dibatasi tulang daun). Spora keunguan di bawah daun.', kerugian: 'Daun cepat mati kering, buah prematur/kerdil.', penanganan: 'Fungisida Mankozeb atau Dimetomorf. Buang daun sakit.', sasaranPestisida: 'Embun Bulu', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Downy_and_Powdery_mildew_on_grape_leaf.JPG' },
  // 11-20
  { nama: 'Embun Tepung (Powdery Mildew)', kategori: 'Jamur', penyebab: 'Oidium sp.', tanaman: ['Mentimun', 'Tomat', 'Kacang'], ciriCiri: 'Serbuk putih/tepung menutupi daun, batang. Daun akhirnya menguning.', kerugian: 'Fotosintesis terhambat drastis, hasil panen turun.', penanganan: 'Fungisida Azoksistrobin atau Tebukonazol. Kurangi kelembaban.', sasaranPestisida: 'Embun Tepung', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Golovinomyces_sordidus_on_Broadleaf_Plantain_-_Plantago_major_%2844171864324%29.jpg/960px-Golovinomyces_sordidus_on_Broadleaf_Plantain_-_Plantago_major_%2844171864324%29.jpg' },
  { nama: 'Rebah Semai (Damping Off)', kategori: 'Jamur', penyebab: 'Pythium spp. / Rhizoctonia', tanaman: ['Cabai', 'Tomat', 'Sawi', 'Kubis'], ciriCiri: 'Pangkal batang bibit kecil membusuk, berair, lalu roboh.', kerugian: 'Kematian massal di nampan persemaian.', penanganan: 'Sterilisasi media tanam, Propamokarb hidroklorida atau Mankozeb.', sasaranPestisida: 'Rebah Semai (Damping Off)', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/00/Pinus_taeda_seedling_damping_off_%28cropped%29.jpg' },
  { nama: 'Mosaik Virus (TMV/CMV)', kategori: 'Virus', penyebab: 'Tobacco/Cucumber Mosaic Virus', tanaman: ['Tomat', 'Cabai', 'Mentimun'], ciriCiri: 'Daun belang-belang kuning-hijau (mosaik), bentuk daun keriting, buah cacat.', kerugian: 'Sangat mudah menular lewat alat gunting, tangan, atau kutu daun (aphid).', penanganan: 'Cabut/bakar tanaman terinfeksi. Semprot Insektisida anti kutu daun.', sasaranPestisida: 'Kutu Daun (Aphids)', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Mosaic_virus_symptoms_on_a_tobacco_leaf.jpg/960px-Mosaic_virus_symptoms_on_a_tobacco_leaf.jpg' },
  { nama: 'Karat Daun', kategori: 'Jamur', penyebab: 'Puccinia sp.', tanaman: ['Kacang', 'Bawang Merah'], ciriCiri: 'Bintil-bintil seperti serbuk karat besi warna oranye/coklat di daun.', kerugian: 'Daun rontok lebih awal, pengisian polong/umbi tidak maksimal.', penanganan: 'Fungisida berbahan aktif Difenokonazol atau Mankozeb.', sasaranPestisida: 'Karat Daun', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Uromyces_viciae-fabae_on_Vicia_faba.jpg/960px-Uromyces_viciae-fabae_on_Vicia_faba.jpg' },
  { nama: 'Busuk Pangkal Batang', kategori: 'Jamur', penyebab: 'Phytophthora capsici', tanaman: ['Cabai', 'Tomat'], ciriCiri: 'Kulit pangkal batang dekat tanah melepuh, coklat hitam dan mengelupas.', kerugian: 'Tanaman mati mendadak seperti layu tapi batang bawah busuk basah.', penanganan: 'Kocorkan Fungisida Tembaga Oksida atau Dimetomorf di area perakaran.', sasaranPestisida: 'Busuk Batang', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Phytophthora_cactorum_01.jpg/960px-Phytophthora_cactorum_01.jpg' },
  { nama: 'Bercak Bakteri (Xanthomonas)', kategori: 'Bakteri', penyebab: 'Xanthomonas campestris', tanaman: ['Cabai', 'Tomat'], ciriCiri: 'Bercak hitam kecil bersudut agak basah di daun, daun mudah rontok.', kerugian: 'Rontok daun massal, buah juga berbintik hitam gabus kasar.', penanganan: 'Bakterisida Tembaga Oksida atau Streptomisin.', sasaranPestisida: 'Bercak Daun Bakteri', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Bacterial_leaf_spot_on_tomato.jpg/960px-Bacterial_leaf_spot_on_tomato.jpg' },
  { nama: 'Mboler / Pucuk Pucat', kategori: 'Jamur', penyebab: 'Fusarium sp.', tanaman: ['Bawang Merah'], ciriCiri: 'Daun pelintir (muntir), pucuk daun menguning layu, akar dan dasar umbi busuk.', kerugian: 'Kerusakan massal di lahan basah, tanaman tidak menghasilkan umbi.', penanganan: 'Fungisida sistemik golongan triazol (Tebukonazol / Difenokonazol).', sasaranPestisida: 'Layu Fusarium', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Fusarium_wilt_symptom_tobacco.jpg/960px-Fusarium_wilt_symptom_tobacco.jpg' },
  { nama: 'Kudis (Scab)', kategori: 'Jamur', penyebab: 'Cladosporium / Elsinoe', tanaman: ['Tomat', 'Cabai', 'Mentimun'], ciriCiri: 'Bercak menonjol kasar, seperti gabus atau kudis pada daun dan buah.', kerugian: 'Menurunkan kualitas kosmetik buah drastis.', penanganan: 'Fungisida Klorotalonil atau Mankozeb preventif.', sasaranPestisida: 'Bercak Daun', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Apple_scab_on_fruit.jpeg/960px-Apple_scab_on_fruit.jpeg' },
  { nama: 'Layu Verticillium', kategori: 'Jamur', penyebab: 'Verticillium dahliae', tanaman: ['Tomat', 'Cabai', 'Kacang'], ciriCiri: 'Layu V-shape di ujung daun, menguning separuh sisi daun.', kerugian: 'Tanaman perlahan kerdil dan mati, sistem vaskular coklat.', penanganan: 'Sangat sulit diobati. Rotasi tanaman, gunakan Trichoderma di awal tanam.', sasaranPestisida: 'Layu Jamur', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Verticillium_dahliae.jpg/960px-Verticillium_dahliae.jpg' },
  { nama: 'Bercak Coklat', kategori: 'Jamur', penyebab: 'Alternaria solani', tanaman: ['Tomat', 'Cabai'], ciriCiri: 'Bercak coklat melingkar konsentris (seperti target sasaran panah) di daun bawah.', kerugian: 'Daun terbawah mati bertahap ke atas.', penanganan: 'Semprot Fungisida Mankozeb atau Azoksistrobin.', sasaranPestisida: 'Bercak Daun', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Alternaria_solani_01.jpg/960px-Alternaria_solani_01.jpg' },
  // 21-25
  { nama: 'Busuk Leher Akar', kategori: 'Jamur', penyebab: 'Sclerotium rolfsii', tanaman: ['Tomat', 'Cabai', 'Kacang'], ciriCiri: 'Layu tiba-tiba, pangkal batang ditutupi miselium putih tebal seperti kapas bersklerotia bulat seperti biji sawi.', kerugian: 'Mematikan tanaman sehat tiba-tiba di musim pancaroba.', penanganan: 'Fungisida Iprodion / Tebukonazol. Cabut segera tanaman sakit.', sasaranPestisida: 'Busuk Batang', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Sclerotium_rolfsii.jpg/960px-Sclerotium_rolfsii.jpg' },
  { nama: 'Serangan Lalat Buah', kategori: 'Hama (Efek Penyakit)', penyebab: 'Bactrocera sp.', tanaman: ['Cabai', 'Tomat', 'Mentimun'], ciriCiri: 'Titik hitam kecil bekas suntikan di buah, buah menguning rontok, berisi belatung.', kerugian: 'Gagal panen buah secara masif dan cepat (buah mulus tapi dalamnya busuk).', penanganan: 'Gunakan Petrogenol (atraktan) perangkap jantan, bungkus buah, Insektisida Deltametrin.', sasaranPestisida: 'Lalat Buah', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Bactrocera_dorsalis.jpg/960px-Bactrocera_dorsalis.jpg' },
  { nama: 'Keriting Daun (Kutu/Thrips)', kategori: 'Hama (Efek Penyakit)', penyebab: 'Kutu Daun, Thrips, Tungau', tanaman: ['Cabai', 'Tomat', 'Mentimun'], ciriCiri: 'Daun keriting, mengerut, melengkung ke atas atau ke bawah, tanaman stunting.', kerugian: 'Tanaman berhenti tumbuh, tidak menghasilkan bunga/buah sama sekali.', penanganan: 'Insektisida / Akarisida (Abamektin, Imidakloprid, Profenofos).', sasaranPestisida: 'Thrips', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Thrips_tabaci.jpg/960px-Thrips_tabaci.jpg' },
  { nama: 'Nematoda Puruh Akar', kategori: 'Hama (Nematoda)', penyebab: 'Meloidogyne spp.', tanaman: ['Cabai', 'Tomat', 'Mentimun'], ciriCiri: 'Tanaman kerdil, layu siang hari, kalau dicabut akar berbenjol-benjol tidak wajar.', kerugian: 'Sistem perakaran hancur, layu prematur.', penanganan: 'Gunakan Nematisida (Karbofuran). Rotasi dengan tanaman non-inang (Tagetes/Bunga Kenikir).', sasaranPestisida: 'Nematoda Bintil Akar', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Root-knot_nematode.jpg/960px-Root-knot_nematode.jpg' },
  { nama: 'Mati Pucuk (Dieback)', kategori: 'Jamur', penyebab: 'Colletotrichum sp. / Phytophthora', tanaman: ['Cabai'], ciriCiri: 'Ujung ranting atau pucuk daun mengering dari atas ke bawah berwarna coklat hitam.', kerugian: 'Cabang mati, bunga rontok, tanaman gundul.', penanganan: 'Pangkas pucuk yang mati lalu semprot Fungisida Propineb.', sasaranPestisida: 'Patek', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Colletotrichum_lindemuthianum.jpg/960px-Colletotrichum_lindemuthianum.jpg' }
];`

let optStart = content.indexOf('const PENYAKIT_OPTIONS = [');
let optEnd = content.indexOf('];', optStart) + 2;
content = content.substring(0, optStart) + newOptions + content.substring(optEnd);

let catStart = content.indexOf('const PENYAKIT_CATALOG = [');
let catEnd = content.indexOf('];', catStart) + 2;
content = content.substring(0, catStart) + newCatalog + content.substring(catEnd);

fs.writeFileSync('src/views/CariPenyakitView.tsx', content);
