const fs = require('fs');
let content = fs.readFileSync('src/views/CariBibitView.tsx', 'utf-8');

const newData = `const CATALOG = [
  // CABAI RAWIT MERAH (15)
  { komoditas: 'Cabai Rawit Merah', nama: 'Ori 212', produsen: 'Aura Seed', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '85-90 HST', potensiHasil: '10-15 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Tahan virus kuning, buah lebat, sangat disukai petani untuk musim kemarau maupun hujan.', kekurangan: 'Ukuran buah relatif lebih kecil dibandingkan varietas hibrida lainnya.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Kaliber', produsen: 'Jogja Seed', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan'], umurPanen: '80-90 HST', potensiHasil: '10-15 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Buah keras, tahan simpan dan angkut, warna merah cerah mengkilap, tahan rontok.', kekurangan: 'Kurang tahan terhadap curah hujan ekstrem, rentan antraknosa jika drainase buruk.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Bara', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '80-85 HST', potensiHasil: '10-15 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Tingkat kepedasan sangat tinggi, adaptasi luas di dataran rendah, buah tipe merunduk.', kekurangan: 'Umur panen sedikit lebih lambat, buah rentan rontok saat kemarau panjang tanpa penyiraman.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Pelita 8 F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-80 HST', potensiHasil: '10-15 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Produktivitas tinggi, bisa dipanen hijau maupun merah, toleran layu bakteri.', kekurangan: 'Kebutuhan pupuk dasar cukup tinggi untuk mencapai potensi maksimal.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Rompis F1', produsen: 'Mutiara Bumi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '85-90 HST', potensiHasil: '10-15 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Tahan antraknosa (patek), genjah, hasil per tanaman sangat tinggi.', kekurangan: 'Cabang kurang kokoh, butuh lanjaran ekstra kuat.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Shypoon', produsen: 'Halbanero', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan'], umurPanen: '80-90 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Ukuran buah panjang dan besar, bobot berat, vigor tanaman kuat.', kekurangan: 'Sangat rentan terhadap layu fusarium pada musim hujan.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Taruna', produsen: 'Bisi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan'], umurPanen: '80-90 HST', potensiHasil: '10-15 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Rawit tipe tegak, sangat pedas, toleran layu dan penyakit daun.', kekurangan: 'Buah tegak rentan masuknya air hujan sehingga mudah busuk.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Dewata 43 F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '65-70 HST', potensiHasil: '12-15 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Umur panen genjah (65 HST), warna buah kuning kehijauan lalu merah cerah.', kekurangan: 'Ukuran buah mengecil di masa panen akhir.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Sret', produsen: 'Bintang Asia', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-80 HST', potensiHasil: '10-15 ton/ha', harga: 'Rp 120.000 / 10gr', keunggulan: 'Buah sangat lebat, tahan layu fusarium, pedas menyengat.', kekurangan: 'Perlu pewiwillan intensif di awal masa tanam.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Pilar F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-80 HST', potensiHasil: '10-15 ton/ha', harga: 'Rp 145.000 / 10gr', keunggulan: 'Toleran virus kuning, sangat genjah, tahan rontok bunga.', kekurangan: 'Warna buah sedikit kusam jika kurang unsur Kalium.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Mhanu F1', produsen: 'Mutiara Bumi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '85-90 HST', potensiHasil: '12-16 ton/ha', harga: 'Rp 130.000 / 10gr', keunggulan: 'Tipe buah menggantung, produksi tinggi, warna merah menyala.', kekurangan: 'Daya simpan kurang lama, cepat mengkerut setelah dipetik.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Bhakti', produsen: 'Bisi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '80-85 HST', potensiHasil: '12-15 ton/ha', harga: 'Rp 115.000 / 10gr', keunggulan: 'Toleran kekeringan, perawatan mudah, buah lebat.', kekurangan: 'Rentan bercak daun jika musim hujan.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Saka', produsen: 'Aura Seed', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan'], umurPanen: '85-90 HST', potensiHasil: '14-18 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Buah besar, panjang, merah merata, tahan pengiriman jauh.', kekurangan: 'Kurang genjah, panen cukup lambat.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Sonar', produsen: 'Bisi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-85 HST', potensiHasil: '10-15 ton/ha', harga: 'Rp 125.000 / 10gr', keunggulan: 'Buah kecil namun super padat, rasa sangat pedas, toleran virus.', kekurangan: 'Pemetikan membutuhkan waktu lama karena buah kecil.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Pusaka 18', produsen: 'Tunas Agro', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '80-85 HST', potensiHasil: '13-16 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Tahan layu fusarium, warna merah cerah, tipe tumbuh tegak.', kekurangan: 'Batang kurang kokoh, wajib dipasang ajir sejak awal.' },

  // CABAI MERAH KERITING (15)
  { komoditas: 'Cabai Merah Keriting', nama: 'Laba F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-85 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Ukuran buah seragam, tahan layu bakteri, umur panen genjah.', kekurangan: 'Panjang buah berkurang pada dataran yang terlalu tinggi.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Lado F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '75-85 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Warna buah merah menyala, potensi hasil sangat tinggi, toleran kemarau.', kekurangan: 'Rentan keriting daun jika terserang thrips.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Akar', produsen: 'Mutiara Bumi', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-85 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Tahan cuaca ekstrem, sangat tahan penyakit antraknosa (patek).', kekurangan: 'Pertumbuhan awal agak lambat.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'OR Twist 42', produsen: 'Oriental Seed', ketinggian: ['Rendah', 'Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-85 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Adaptasi sangat luas, buah keriting sempurna, disukai pasar tradisional.', kekurangan: 'Sangat membutuhkan suplai kalsium agar ujung buah tidak busuk.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Lolai F1', produsen: 'Bintang Asia', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-85 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Tahan virus, buah lebat, panjang buah seragam hingga pucuk.', kekurangan: 'Kurang tahan genangan air.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Kastilo F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-85 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Toleran layu bakteri dan busuk batang, umur genjah, hasil tinggi.', kekurangan: 'Bobot per buah lebih ringan dibanding kompetitor.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Rimba F1', produsen: 'Tunas Agro', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan'], umurPanen: '80-90 HST', potensiHasil: '18-22 ton/ha', harga: 'Rp 145.000 / 10gr', keunggulan: 'Tahan layu fusarium, adaptasi dataran tinggi sangat baik, buah besar panjang.', kekurangan: 'Umur panen cukup lambat.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Sios Tavi', produsen: 'Bisi', ketinggian: ['Rendah', 'Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '80-85 HST', potensiHasil: '16-18 ton/ha', harga: 'Rp 145.000 / 10gr', keunggulan: 'Ketahanan ekstra terhadap Gemini Virus (Tavi), pemeliharaan relatif mudah.', kekurangan: 'Daya tumbuh benih sedikit lambat.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Iggo', produsen: 'Bintang Asia', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '75-80 HST', potensiHasil: '15-18 ton/ha', harga: 'Rp 130.000 / 10gr', keunggulan: 'Sangat genjah, merah mengkilap, tahan kering.', kekurangan: 'Kurang cocok untuk musim hujan yang terus menerus.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Jitu', produsen: 'Mutiara Bumi', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '85-95 HST', potensiHasil: '18-20 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Tahan layu bakteri, bobot berat, diameter buah pas untuk pasar lokal.', kekurangan: 'Butuh penyangga ganda karena buah sangat lebat.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'PM 999 F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '80-85 HST', potensiHasil: '16-18 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Kualitas buah prima, disukai pengepul besar, toleran patek.', kekurangan: 'Tingkat kepedasan tergolong sedang.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Red Saber', produsen: 'Known You Seed', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Kemarau'], umurPanen: '85-90 HST', potensiHasil: '15-18 ton/ha', harga: 'Rp 150.000 / 10gr', keunggulan: 'Bentuk sangat keriting dan menarik, merah cerah, keras.', kekurangan: 'Harga benih lebih mahal.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Tangguh F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '80-85 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Sangat kokoh dan tahan rebah, daya simpan paska panen lama.', kekurangan: 'Respons terhadap kekurangan air cukup cepat (mudah layu).' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Vigo', produsen: 'Tunas Agro', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan'], umurPanen: '80-85 HST', potensiHasil: '15-18 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Toleran layu fusarium di dataran tinggi, pangkal buah tebal.', kekurangan: 'Butuh pemupukan P (Fosfat) tinggi di awal.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Zafira', produsen: 'Aura Seed', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '75-80 HST', potensiHasil: '14-17 ton/ha', harga: 'Rp 130.000 / 10gr', keunggulan: 'Panen cepat, tahan virus kuning, rasa pedas kuat.', kekurangan: 'Tanaman kurang rimbun.' },

  // CABAI MERAH BESAR (10)
  { komoditas: 'Cabai Merah Besar', nama: 'Gada F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-80 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 145.000 / 10gr', keunggulan: 'Ukuran buah besar (bisa >15cm), merah mengkilap, tebal.', kekurangan: 'Rentan antraknosa di musim hujan.' },
  { komoditas: 'Cabai Merah Besar', nama: 'Gada MK F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '75-80 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 150.000 / 10gr', keunggulan: 'Perbaikan dari Gada F1, lebih tahan kemarau dan keriting daun.', kekurangan: 'Masih rentan patek saat curah hujan mendadak.' },
  { komoditas: 'Cabai Merah Besar', nama: 'Baja F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-80 HST', potensiHasil: '16-20 ton/ha', harga: 'Rp 155.000 / 10gr', keunggulan: 'Toleran layu bakteri, umur genjah, sangat disukai pedagang besar.', kekurangan: 'Kebutuhan nutrisi mikro sangat tinggi untuk mencegah buah bengkok.' },
  { komoditas: 'Cabai Merah Besar', nama: 'Senopati F1', produsen: 'Bisi', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '85-90 HST', potensiHasil: '18-22 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Cocok di dataran tinggi, buah tebal, tahan simpan dan transportasi.', kekurangan: 'Ukuran tanaman cukup tinggi, butuh lanjaran panjang.' },
  { komoditas: 'Cabai Merah Besar', nama: 'Imperial 10 F1', produsen: 'Bisi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '80-85 HST', potensiHasil: '16-20 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Ukuran sangat jumbo, panjang dan lurus, merah merata.', kekurangan: 'Sangat rentan terserang lalat buah karena daging tebal manis.' },
  { komoditas: 'Cabai Merah Besar', nama: 'Panex 100 F1', produsen: 'Panah Merah', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '85-90 HST', potensiHasil: '18-20 ton/ha', harga: 'Rp 150.000 / 10gr', keunggulan: 'Tahan layu fusarium, kulit buah mulus, sangat cocok untuk dataran tinggi.', kekurangan: 'Warna buah saat hijau tergolong pucat sebelum menjadi merah sempurna.' },
  { komoditas: 'Cabai Merah Besar', nama: 'Wibawa F1', produsen: 'Tunas Agro', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan'], umurPanen: '80-85 HST', potensiHasil: '15-18 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Toleran genangan air, buah tidak mudah pecah, toleran layu.', kekurangan: 'Diameter buah sedikit lebih kecil dibanding Baja F1.' },
  { komoditas: 'Cabai Merah Besar', nama: 'Horison 97', produsen: 'Bintang Asia', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '80-85 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Sangat produktif di musim kemarau, tahan virus Gemini.', kekurangan: 'Daun sangat lebar sehingga sirkulasi udara bisa terhambat jika jarak tanam rapat.' },
  { komoditas: 'Cabai Merah Besar', nama: 'Columbus', produsen: 'Mutiara Bumi', ketinggian: ['Rendah', 'Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '80-90 HST', potensiHasil: '16-20 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Vigor kuat, daya adaptasi luas, tahan layu bakteri.', kekurangan: 'Panen agak sulit karena tangkai buah keras.' },
  { komoditas: 'Cabai Merah Besar', nama: 'Elegance', produsen: 'Known You Seed', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Kemarau'], umurPanen: '90-95 HST', potensiHasil: '15-18 ton/ha', harga: 'Rp 160.000 / 10gr', keunggulan: 'Bentuk buah sangat indah dan seragam, warna merah sangat gelap (premium).', kekurangan: 'Benih mahal, umur panen sangat lambat.' },

  // TOMAT (10)
  { komoditas: 'Tomat', nama: 'Servo F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '65-70 HST', potensiHasil: '40-60 ton/ha', harga: 'Rp 120.000 / 10gr', keunggulan: 'Tahan Virus Kuning (Gemini), produksi sangat tinggi, buah keras tahan simpan.', kekurangan: 'Sangat rentan penyakit busuk daun (Phytophthora) saat musim hujan ekstrem.' },
  { komoditas: 'Tomat', nama: 'Gustavi F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '70-75 HST', potensiHasil: '50-60 ton/ha', harga: 'Rp 125.000 / 10gr', keunggulan: 'Buah ukuran jumbo di dataran rendah, bobot berat, merah merata.', kekurangan: 'Membutuhkan lanjaran yang sangat kuat karena beban buah sangat berat.' },
  { komoditas: 'Tomat', nama: 'Tymoti F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '60-65 HST', potensiHasil: '50-60 ton/ha', harga: 'Rp 130.000 / 10gr', keunggulan: 'Umur genjah, tahan virus, ukuran seragam dari bawah hingga pucuk.', kekurangan: 'Daun agak tipis, rentan kutu daun dan thrips.' },
  { komoditas: 'Tomat', nama: 'Betavila F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '70-75 HST', potensiHasil: '40-50 ton/ha', harga: 'Rp 115.000 / 10gr', keunggulan: 'Toleran layu bakteri, cocok untuk dataran rendah yang rawan layu.', kekurangan: 'Buah kurang keras jika kekurangan kalsium.' },
  { komoditas: 'Tomat', nama: 'Corona', produsen: 'Bintang Asia', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '80-85 HST', potensiHasil: '60-70 ton/ha', harga: 'Rp 110.000 / 10gr', keunggulan: 'Buah sangat besar, tipe indeterminate, tahan layu fusarium.', kekurangan: 'Hanya optimal di dataran tinggi, di dataran rendah buah mengecil.' },
  { komoditas: 'Tomat', nama: 'Chung', produsen: 'Lokal', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '60-65 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 20.000 / 10gr', keunggulan: 'Tomat ranti/sayur berukuran kecil, rasa sangat asam segar untuk sambal, tahan banting.', kekurangan: 'Hasil tidak sebanyak hibrida, daya simpan singkat.' },
  { komoditas: 'Tomat', nama: 'Fortuna F1', produsen: 'Bisi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan'], umurPanen: '70-75 HST', potensiHasil: '45-55 ton/ha', harga: 'Rp 120.000 / 10gr', keunggulan: 'Tahan layu bakteri, cocok untuk musim penghujan.', kekurangan: 'Warna buah sedikit pucat dibanding Servo.' },
  { komoditas: 'Tomat', nama: 'Marta F1', produsen: 'Bisi', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '80-85 HST', potensiHasil: '60-80 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Potensi hasil luar biasa besar, buah daging tebal, indeterminate.', kekurangan: 'Panen lambat, butuh perawatan intensif.' },
  { komoditas: 'Tomat', nama: 'Amelia', produsen: 'Tunas Agro', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '65-70 HST', potensiHasil: '40-50 ton/ha', harga: 'Rp 110.000 / 10gr', keunggulan: 'Sangat genjah, tahan virus, produksi awal sangat tinggi.', kekurangan: 'Kurang tahan cuaca ekstrem basah.' },
  { komoditas: 'Tomat', nama: 'Natali F1', produsen: 'Tunas Agro', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan'], umurPanen: '80-85 HST', potensiHasil: '50-60 ton/ha', harga: 'Rp 120.000 / 10gr', keunggulan: 'Toleran busuk daun di musim hujan, merah cerah merata.', kekurangan: 'Kurang optimal di dataran rendah.' },

  // BAWANG MERAH (5)
  { komoditas: 'Bawang Merah', nama: 'Bima Brebes', produsen: 'Benih Umbi Lokal', ketinggian: ['Rendah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '60-65 HST', potensiHasil: '10-15 ton/ha', harga: 'Rp 35.000 / kg', keunggulan: 'Warna merah menyala, aroma tajam, ukuran seragam, paling dicari pasar.', kekurangan: 'Sangat rentan penyakit pucuk pucat (mboler) saat curah hujan tinggi.' },
  { komoditas: 'Bawang Merah', nama: 'Bauji', produsen: 'Benih Umbi Lokal', ketinggian: ['Rendah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '60-65 HST', potensiHasil: '12-16 ton/ha', harga: 'Rp 30.000 / kg', keunggulan: 'Ukuran umbi besar, tahan hujan, tahan pengangkutan jauh.', kekurangan: 'Warna tidak semerah Bima Brebes, agak pucat saat awal panen.' },
  { komoditas: 'Bawang Merah', nama: 'Tajuk', produsen: 'Benih Umbi Lokal', ketinggian: ['Rendah'], cuaca: ['Kemarau'], umurPanen: '65-70 HST', potensiHasil: '10-14 ton/ha', harga: 'Rp 32.000 / kg', keunggulan: 'Umbi besar dan padat, tahan cuaca panas kering, cocok di tanah berpasir.', kekurangan: 'Kurang cocok ditanam saat puncak musim hujan.' },
  { komoditas: 'Bawang Merah (Biji)', nama: 'Tuktuk', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '75-80 HST (dari semai)', potensiHasil: '15-20 ton/ha', harga: 'Rp 180.000 / 50gr', keunggulan: 'Bawang merah dari biji (TSS), hasil umbi besar tunggal, bebas virus bawaan umbi.', kekurangan: 'Waktu budidaya sangat panjang (harus semai), perawatan awal sulit.' },
  { komoditas: 'Bawang Merah (Biji)', nama: 'Lokandi', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-80 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 190.000 / 50gr', keunggulan: 'Lebih tahan cuaca ekstrem dibanding Tuktuk, warna umbi merah merata.', kekurangan: 'Tetap membutuhkan teknik semai biji (TSS) yang presisi.' },

  // MENTIMUN (5)
  { komoditas: 'Mentimun', nama: 'Zatavy F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '35-40 HST', potensiHasil: '45-55 ton/ha', harga: 'Rp 75.000 / 20gr', keunggulan: 'Tahan Gemini Virus, warna buah hijau merata, tahan simpan.', kekurangan: 'Tanaman butuh air yang sangat cukup saat pembentukan buah.' },
  { komoditas: 'Mentimun', nama: 'Mercy F1', produsen: 'Bisi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '33-36 HST', potensiHasil: '50-60 ton/ha', harga: 'Rp 80.000 / 20gr', keunggulan: 'Buah sangat lebat, panen cepat, warna hijau cerah menarik pasar.', kekurangan: 'Rasa bagian pangkal terkadang sedikit pahit jika stres air.' },
  { komoditas: 'Mentimun', nama: 'Hercules', produsen: 'Bintang Asia', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '35-40 HST', potensiHasil: '40-50 ton/ha', harga: 'Rp 60.000 / 20gr', keunggulan: 'Buah ukuran besar (tipe lalap dan sayur), tidak pahit.', kekurangan: 'Kurang tahan rebah jika angin kencang.' },
  { komoditas: 'Mentimun', nama: 'Metavy F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '35-40 HST', potensiHasil: '45-50 ton/ha', harga: 'Rp 70.000 / 20gr', keunggulan: 'Toleran kekeringan, buah lebat dari bawah sampai atas.', kekurangan: 'Lebih rentan penyakit jamur di musim hujan lebat.' },
  { komoditas: 'Mentimun', nama: 'Wulan', produsen: 'Tunas Agro', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan'], umurPanen: '35-40 HST', potensiHasil: '45-50 ton/ha', harga: 'Rp 65.000 / 20gr', keunggulan: 'Tahan layu fusarium, warna hijau gelap, cocok musim hujan.', kekurangan: 'Diameter buah sedikit lebih kurus.' },

  // KUBIS / SAWI / PAKCOY / BAYAM / KANGKUNG / SELADA (30)
  { komoditas: 'Kubis', nama: 'Green Nova', produsen: 'Takii Seed', ketinggian: ['Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '70-75 HST', potensiHasil: '35-40 ton/ha', harga: 'Rp 150.000 / 20gr', keunggulan: 'Krop padat, besar, tahan akar gada dan busuk hitam.', kekurangan: 'Hanya optimal di dataran tinggi >800 mdpl.' },
  { komoditas: 'Kubis', nama: 'Sehati', produsen: 'Bintang Asia', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '65-70 HST', potensiHasil: '25-30 ton/ha', harga: 'Rp 80.000 / 20gr', keunggulan: 'Bisa ditanam di dataran rendah, krop lumayan padat.', kekurangan: 'Ukuran krop tidak sebesar varietas dataran tinggi.' },
  { komoditas: 'Kubis', nama: 'KK Cross', produsen: 'Takii Seed', ketinggian: ['Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '60-65 HST', potensiHasil: '30-40 ton/ha', harga: 'Rp 160.000 / 20gr', keunggulan: 'Sangat genjah, krop padat membulat, tahan angkut jauh.', kekurangan: 'Harga benih mahal.' },
  { komoditas: 'Kubis', nama: 'Grondal', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '70-75 HST', potensiHasil: '25-35 ton/ha', harga: 'Rp 75.000 / 20gr', keunggulan: 'Toleran panas, cocok untuk dataran rendah-menengah.', kekurangan: 'Rentan serangan ulat plutella.' },
  { komoditas: 'Kubis', nama: 'Cepat', produsen: 'Cap Kapal Terbang', ketinggian: ['Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '60-65 HST', potensiHasil: '30-40 ton/ha', harga: 'Rp 140.000 / 20gr', keunggulan: 'Cepat panen, kualitas pasar ekspor, tahan penyakit daun.', kekurangan: 'Kurang tahan akar gada.' },
  
  { komoditas: 'Sawi Hijau (Caisim)', nama: 'Shinta', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '25-30 HST', potensiHasil: '25-30 ton/ha', harga: 'Rp 30.000 / 50gr', keunggulan: 'Batang renyah, daun tebal tidak berserat, tahan hujan.', kekurangan: 'Cepat berbunga jika telat panen.' },
  { komoditas: 'Sawi Hijau (Caisim)', nama: 'Tosakan', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '25-30 HST', potensiHasil: '25-30 ton/ha', harga: 'Rp 30.000 / 50gr', keunggulan: 'Sangat seragam, batang besar tegak, daun hijau segar.', kekurangan: 'Perlu banyak air di musim kemarau.' },
  { komoditas: 'Sawi Hijau (Caisim)', nama: 'Kumala', produsen: 'Bintang Asia', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '25-30 HST', potensiHasil: '25-30 ton/ha', harga: 'Rp 25.000 / 50gr', keunggulan: 'Toleran kekeringan, batang panjang kokoh.', kekurangan: 'Daun agak tipis.' },
  { komoditas: 'Sawi Hijau (Caisim)', nama: 'Dora', produsen: 'Cap Kapal Terbang', ketinggian: ['Rendah', 'Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '25-30 HST', potensiHasil: '25-30 ton/ha', harga: 'Rp 28.000 / 50gr', keunggulan: 'Tahan virus, daun lebar, vigor tanaman bagus.', kekurangan: 'Sedikit pahit jika kurang pupuk kandang.' },
  { komoditas: 'Sawi Putih', nama: 'Eikun', produsen: 'Takii Seed', ketinggian: ['Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '60-65 HST', potensiHasil: '40-50 ton/ha', harga: 'Rp 80.000 / 20gr', keunggulan: 'Krop besar silindris, padat, tahan busuk lunak.', kekurangan: 'Hanya optimal di dataran tinggi.' },
  { komoditas: 'Sawi Putih', nama: 'Autumn Sun', produsen: 'Takii Seed', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '60-65 HST', potensiHasil: '40-50 ton/ha', harga: 'Rp 85.000 / 20gr', keunggulan: 'Toleran suhu agak panas (dataran menengah), krop cukup padat.', kekurangan: 'Rentan ulat krop pada suhu tinggi.' },
  { komoditas: 'Sawi Pahit', nama: 'Morakot', produsen: 'Bintang Asia', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '35-40 HST', potensiHasil: '20-25 ton/ha', harga: 'Rp 35.000 / 50gr', keunggulan: 'Daun lebar keriting, rasa pahit khas yang disukai, cocok untuk sayur asin.', kekurangan: 'Rentan kutu daun (aphids).' },
  
  { komoditas: 'Pakcoy', nama: 'Nauli F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '25-30 HST', potensiHasil: '25-30 ton/ha', harga: 'Rp 40.000 / 20gr', keunggulan: 'Batang putih tebal (sendok), renyah, tahan cuaca panas.', kekurangan: 'Mudah terserang bercak daun di musim hujan lebat.' },
  { komoditas: 'Pakcoy', nama: 'Green', produsen: 'Cap Kapal Terbang', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '25-30 HST', potensiHasil: '25-30 ton/ha', harga: 'Rp 35.000 / 20gr', keunggulan: 'Warna sangat hijau gelap, bentuk batang sangat bagus seperti mangkuk.', kekurangan: 'Daun mudah robek saat dikemas jika kurang hati-hati.' },
  { komoditas: 'Pakcoy', nama: 'White', produsen: 'Bintang Asia', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '25-30 HST', potensiHasil: '25-30 ton/ha', harga: 'Rp 30.000 / 20gr', keunggulan: 'Batang ekstra putih, sangat disukai untuk tumis restoran.', kekurangan: 'Rentan dimakan siput/bekicot.' },

  { komoditas: 'Selada', nama: 'Grand Rapids', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '30-40 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 45.000 / 20gr', keunggulan: 'Selada keriting hijau cerah, cocok untuk hidroponik maupun tanah.', kekurangan: 'Cepat kutilang (batang memanjang) jika kurang cahaya matahari.' },
  { komoditas: 'Selada', nama: 'Kriya', produsen: 'Bintang Asia', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '30-40 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 40.000 / 20gr', keunggulan: 'Toleran cuaca panas (tidak mudah bolting/berbunga), rasa manis renyah.', kekurangan: 'Warna hijau sedikit pucat.' },
  { komoditas: 'Selada Merah', nama: 'Red Star', produsen: 'Known You Seed', ketinggian: ['Rendah', 'Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '35-45 HST', potensiHasil: '15-18 ton/ha', harga: 'Rp 70.000 / 20gr', keunggulan: 'Warna merah menarik, kaya antioksidan, nilai jual tinggi.', kekurangan: 'Pertumbuhan agak lambat dibanding selada hijau.' },

  { komoditas: 'Bayam', nama: 'Maestro', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '20-25 HST', potensiHasil: '10-15 ton/ha', harga: 'Rp 30.000 / 50gr', keunggulan: 'Bayam hijau cabut, batang tunggal tanpa cabang samping, sangat seragam.', kekurangan: 'Daun agak rentan ulat grayak.' },
  { komoditas: 'Bayam', nama: 'Giti Merah', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '20-25 HST', potensiHasil: '10-15 ton/ha', harga: 'Rp 35.000 / 50gr', keunggulan: 'Bayam cabut daun warna merah cerah merata.', kekurangan: 'Warna kadang luntur jadi hijau jika terlalu banyak nitrogen.' },
  { komoditas: 'Bayam', nama: 'Baret', produsen: 'Bintang Asia', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '20-25 HST', potensiHasil: '10-15 ton/ha', harga: 'Rp 28.000 / 50gr', keunggulan: 'Bayam belang (merah hijau), vigor sangat kuat.', kekurangan: 'Bentuk warna kurang disukai di beberapa daerah.' },

  { komoditas: 'Kangkung', nama: 'Salina', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '20-25 HST', potensiHasil: '25-30 ton/ha', harga: 'Rp 65.000 / 500gr', keunggulan: 'Kangkung cabut, batang renyah tidak berserat, umur genjah.', kekurangan: 'Sangat rakus air, jika kering langsung kerdil.' },
  { komoditas: 'Kangkung', nama: 'Bika', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '20-25 HST', potensiHasil: '25-30 ton/ha', harga: 'Rp 65.000 / 500gr', keunggulan: 'Bentuk daun lebih lebar/bulat (kangkung ruyung), sangat seragam.', kekurangan: 'Warna daun sedikit lebih muda.' },
  { komoditas: 'Kangkung', nama: 'Mahar', produsen: 'Bintang Asia', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '20-25 HST', potensiHasil: '25-30 ton/ha', harga: 'Rp 60.000 / 500gr', keunggulan: 'Daun pita (memanjang), tahan banting terhadap cuaca ekstrim.', kekurangan: 'Tangkai sedikit lebih keras jika telat panen.' },

  // BROKOLI & KEMBANG KOL (5)
  { komoditas: 'Brokoli', nama: 'Green Magic F1', produsen: 'Sakata', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '55-65 HST', potensiHasil: '20-25 ton/ha', harga: 'Rp 180.000 / 10gr', keunggulan: 'Bunga hijau padat berbentuk kubah, tahan suhu agak hangat.', kekurangan: 'Benih sangat mahal, perlu banyak boron untuk cegah batang berongga.' },
  { komoditas: 'Brokoli', nama: 'Lucky', produsen: 'Known You Seed', ketinggian: ['Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '60-65 HST', potensiHasil: '20-25 ton/ha', harga: 'Rp 150.000 / 10gr', keunggulan: 'Massa bunga besar dan padat, warna hijau kebiruan segar.', kekurangan: 'Kurang cocok ditanam di bawah 800 mdpl.' },
  { komoditas: 'Kembang Kol', nama: 'PM 126 F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '45-50 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Kembang kol khusus dataran rendah, tahan panas, sangat genjah.', kekurangan: 'Ukuran krop tidak terlalu besar (sekitar 0.5-0.8 kg/tanaman).' },
  { komoditas: 'Kembang Kol', nama: 'Aquina', produsen: 'Bintang Asia', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '45-50 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 130.000 / 10gr', keunggulan: 'Bunga putih bersih, krop padat, toleran cekaman kekeringan.', kekurangan: 'Daun pelindung kurang menutup bunga sehingga mudah kuning kena matahari.' },
  { komoditas: 'Kembang Kol', nama: 'Diamond', produsen: 'Known You Seed', ketinggian: ['Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '55-65 HST', potensiHasil: '20-25 ton/ha', harga: 'Rp 150.000 / 10gr', keunggulan: 'Bunga sangat besar padat putih bersih, untuk dataran tinggi.', kekurangan: 'Membutuhkan tanah yang sangat subur dan kaya bahan organik.' },

  // TERONG / KACANG PANJANG / BUNCIS (15)
  { komoditas: 'Terong', nama: 'Yuvita F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '50-60 HST', potensiHasil: '50-60 ton/ha', harga: 'Rp 65.000 / 10gr', keunggulan: 'Terong ungu panjang, buah mulus mengkilap, tahan layu bakteri.', kekurangan: 'Kulit buah mudah tergores, perlu penanganan ekstra saat panen.' },
  { komoditas: 'Terong', nama: 'Mustang F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '50-60 HST', potensiHasil: '50-60 ton/ha', harga: 'Rp 70.000 / 10gr', keunggulan: 'Terong ungu tebal, daging empuk tidak pahit, sangat produktif.', kekurangan: 'Butuh banyak air di fase pembuahan.' },
  { komoditas: 'Terong', nama: 'Lezata', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '50-60 HST', potensiHasil: '50-60 ton/ha', harga: 'Rp 65.000 / 10gr', keunggulan: 'Terong ungu mengkilap, lebat, usia panen panjang.', kekurangan: 'Rentan penyakit kutu kebul.' },
  { komoditas: 'Terong', nama: 'Ratih Hijau', produsen: 'Bintang Asia', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '50-60 HST', potensiHasil: '50-60 ton/ha', harga: 'Rp 60.000 / 10gr', keunggulan: 'Terong hijau panjang, manis renyah, tahan layu.', kekurangan: 'Warna buah memucat di ujung masa panen.' },
  { komoditas: 'Terong', nama: 'Lalap Hijau', produsen: 'Tunas Agro', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '45-50 HST', potensiHasil: '40-50 ton/ha', harga: 'Rp 50.000 / 10gr', keunggulan: 'Terong bulat lalap, renyah manis tidak getir.', kekurangan: 'Mudah rontok buah jika terserang thrips.' },

  { komoditas: 'Kacang Panjang', nama: 'Kanton Tavi', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '45-50 HST', potensiHasil: '25-30 ton/ha', harga: 'Rp 80.000 / 500gr', keunggulan: 'Tahan Virus Kuning (Gemini/MYMV), polong keras hijau cerah, tahan simpan.', kekurangan: 'Benih agak mahal.' },
  { komoditas: 'Kacang Panjang', nama: 'Parade Tavi', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '45-50 HST', potensiHasil: '25-30 ton/ha', harga: 'Rp 85.000 / 500gr', keunggulan: 'Polong sangat panjang (bisa 80cm), tahan virus, lebat menyatu dari bawah.', kekurangan: 'Butuh ajir yang tinggi dan kuat.' },
  { komoditas: 'Kacang Panjang', nama: 'Katrina', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '45-50 HST', potensiHasil: '20-25 ton/ha', harga: 'Rp 70.000 / 500gr', keunggulan: 'Toleran panas, daun rimbun, umur panen sangat genjah.', kekurangan: 'Polong lebih pendek dibanding Parade.' },
  { komoditas: 'Kacang Panjang', nama: 'Sabrina', produsen: 'Bintang Asia', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '45-50 HST', potensiHasil: '25-30 ton/ha', harga: 'Rp 75.000 / 500gr', keunggulan: 'Polong warna hijau tua merata, buntut tidak merah, manis.', kekurangan: 'Rentan karat daun di cuaca terlalu lembab.' },
  { komoditas: 'Kacang Panjang', nama: 'Kencana', produsen: 'Bisi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '45-50 HST', potensiHasil: '25-30 ton/ha', harga: 'Rp 70.000 / 500gr', keunggulan: 'Umur panjang, panen berkali-kali, polong renyah.', kekurangan: 'Kurang tahan virus kuning.' },

  { komoditas: 'Buncis', nama: 'Pertiwi', produsen: 'Benih Pertiwi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '45-50 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 65.000 / 500gr', keunggulan: 'Buncis tegak (tanpa lanjaran), polong gilig renyah.', kekurangan: 'Masa panen cepat habis dibanding tipe merambat.' },
  { komoditas: 'Buncis', nama: 'Lebat-3', produsen: 'Bintang Asia', ketinggian: ['Rendah', 'Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '45-50 HST', potensiHasil: '20-25 ton/ha', harga: 'Rp 70.000 / 500gr', keunggulan: 'Tipe merambat, polong hijau terang mulus tanpa serat (stringless).', kekurangan: 'Butuh biaya lanjaran/ajir.' },
  { komoditas: 'Buncis', nama: 'Gypsy', produsen: 'Known You Seed', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '50-60 HST', potensiHasil: '20-25 ton/ha', harga: 'Rp 80.000 / 500gr', keunggulan: 'Buncis buncis perancis (baby buncis) kualitas premium super manis.', kekurangan: 'Hanya maksimal di daerah sejuk.' },
  { komoditas: 'Buncis', nama: 'Polo', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '45-50 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 65.000 / 500gr', keunggulan: 'Tegak tanpa lanjaran, hasil sangat lebat di dataran rendah.', kekurangan: 'Rentan penyakit layu fusarium.' },
  { komoditas: 'Buncis', nama: 'Maxipro', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '45-50 HST', potensiHasil: '20-25 ton/ha', harga: 'Rp 70.000 / 500gr', keunggulan: 'Merambat, polong silindris, daging sangat tebal biji tidak menonjol.', kekurangan: 'Daya cambah benih kadang tidak merata.' },

  // JAGUNG MANIS / MELON / SEMANGKA / PEPAYA / PADI (15)
  { komoditas: 'Jagung Manis', nama: 'Bonanza F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '70-75 HST', potensiHasil: '14-18 ton/ha', harga: 'Rp 140.000 / 250gr', keunggulan: 'Rasa sangat manis, tongkol besar silindris penuh sampai ujung, tahan bulai.', kekurangan: 'Harga benih mahal, rentan serangan ulat grayak jagung (FAW).' },
  { komoditas: 'Jagung Manis', nama: 'Exotic', produsen: 'Bisi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '70-75 HST', potensiHasil: '14-18 ton/ha', harga: 'Rp 130.000 / 250gr', keunggulan: 'Toleran penyakit karat daun dan hawar, tongkol seragam manis.', kekurangan: 'Ukuran tongkol sedikit lebih kecil dari Bonanza.' },
  { komoditas: 'Jagung Manis', nama: 'Talenta', produsen: 'Bisi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '70-75 HST', potensiHasil: '14-18 ton/ha', harga: 'Rp 125.000 / 250gr', keunggulan: 'Tahan kering, manis dan daya simpan lama sesudah dipanen.', kekurangan: 'Rentan bulai (Peronosclerospora) di musim penghujan.' },

  { komoditas: 'Melon', nama: 'Action 434', produsen: 'Known You Seed', ketinggian: ['Rendah'], cuaca: ['Kemarau'], umurPanen: '65-70 HST', potensiHasil: '25-30 ton/ha', harga: 'Rp 150.000 / 15gr', keunggulan: 'Net (jaring) tebal dan cantik, daging tebal manis (brix 13-15%), tahan angkut.', kekurangan: 'Sangat rentan embun bulu (downy mildew) saat musim hujan.' },
  { komoditas: 'Melon', nama: 'Pertivi F1', produsen: 'Benih Pertiwi', ketinggian: ['Rendah'], cuaca: ['Kemarau'], umurPanen: '60-65 HST', potensiHasil: '25-30 ton/ha', harga: 'Rp 120.000 / 15gr', keunggulan: 'Warna daging hijau segar, genjah, buah besar (2-3 kg).', kekurangan: 'Kurang tahan layu fusarium.' },
  { komoditas: 'Melon', nama: 'Golden Langkawi', produsen: 'Known You Seed', ketinggian: ['Rendah'], cuaca: ['Kemarau'], umurPanen: '65-70 HST', potensiHasil: '25-30 ton/ha', harga: 'Rp 160.000 / 15gr', keunggulan: 'Kulit kuning mulus tanpa net, daging putih sangat manis (brix 15-16%).', kekurangan: 'Kulit rentan pecah jika kelebihan air.' },

  { komoditas: 'Semangka', nama: 'Inul Kuning', produsen: 'Bintang Asia', ketinggian: ['Rendah'], cuaca: ['Kemarau'], umurPanen: '60-65 HST', potensiHasil: '25-35 ton/ha', harga: 'Rp 130.000 / 20gr', keunggulan: 'Bentuk lonjong, daging buah kuning segar, sangat manis dan renyah.', kekurangan: 'Tidak bisa tahan air menggenang lama.' },
  { komoditas: 'Semangka', nama: 'Bintang (Inul Merah)', produsen: 'Bintang Asia', ketinggian: ['Rendah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '60-65 HST', potensiHasil: '25-35 ton/ha', harga: 'Rp 120.000 / 20gr', keunggulan: 'Semangka inul merah, daging padat, tahan layu fusarium.', kekurangan: 'Kulit cukup tipis, hati-hati saat pengangkutan jauh.' },
  { komoditas: 'Semangka', nama: 'Bagus (Non Biji)', produsen: 'Bintang Asia', ketinggian: ['Rendah'], cuaca: ['Kemarau'], umurPanen: '65-70 HST', potensiHasil: '30-40 ton/ha', harga: 'Rp 150.000 / 20gr', keunggulan: 'Semangka tanpa biji bulat besar, merah merata, sangat disukai.', kekurangan: 'Wajib tanam semangka berbiji untuk penyerbukan (polinasi).' },

  { komoditas: 'Pepaya', nama: 'California (Callina)', produsen: 'IPB', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '7-9 Bulan', potensiHasil: '80-100 ton/ha', harga: 'Rp 40.000 / 10gr', keunggulan: 'Rasa manis legit, daging merah tebal, pohon kerdil sudah berbuah.', kekurangan: 'Rentan penyakit antraknosa (patek) dan busuk akar di lahan lembab.' },
  { komoditas: 'Pepaya', nama: 'Bangkok', produsen: 'Lokal Unggul', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '8-10 Bulan', potensiHasil: '100-120 ton/ha', harga: 'Rp 30.000 / 10gr', keunggulan: 'Buah sangat jumbo (bisa >3 kg), tahan penyakit kuning.', kekurangan: 'Pohon sangat tinggi seiring waktu, rasa kurang manis manis dibanding California.' },

  { komoditas: 'Padi', nama: 'Inpari 32', produsen: 'Balitbangtan', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '120 HST', potensiHasil: '6-8 ton/ha', harga: 'Rp 15.000 / kg', keunggulan: 'Sangat tahan penyakit hawar daun bakteri (HDB/kresek) dan blas daun, beras pulen.', kekurangan: 'Batang agak tinggi, berpotensi rebah saat angin kencang campur hujan deras.' },
  { komoditas: 'Padi', nama: 'Inpari 42', produsen: 'Balitbangtan', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '112 HST', potensiHasil: '7-9 ton/ha', harga: 'Rp 16.000 / kg', keunggulan: 'Umur genjah, batang kokoh anti rebah, beras bening tanpa perut putih.', kekurangan: 'Sedikit rentan terhadap wereng coklat (WBC) biotipe baru.' },
  { komoditas: 'Padi', nama: 'Ciherang', produsen: 'Balitbangtan', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '115-125 HST', potensiHasil: '6-8 ton/ha', harga: 'Rp 14.000 / kg', keunggulan: 'Paling populer pulennya dan harga jual tinggi, adaptasi sangat luas.', kekurangan: 'Sangat rentan penyakit hawar daun (kresek) dan blas saat musim hujan.' },
  { komoditas: 'Padi', nama: 'Mapan P-05 F1', produsen: 'Primasid', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '115-120 HST', potensiHasil: '8-11 ton/ha', harga: 'Rp 95.000 / kg', keunggulan: 'Padi hibrida, anakan sangat banyak, malai panjang, hasil gabah super tinggi.', kekurangan: 'Harga benih mahal, tidak bisa dijadikan benih lagi untuk musim berikutnya.' }
];`;

let startIdx = content.indexOf('const CATALOG = [');
let endIdx = content.indexOf('];', startIdx) + 2;

content = content.substring(0, startIdx) + newData + content.substring(endIdx);

fs.writeFileSync('src/views/CariBibitView.tsx', content);
