const fs = require('fs');
let content = fs.readFileSync('src/views/CariBibitView.tsx', 'utf-8');

const newCatalog = `const CATALOG = [
  // CABAI RAWIT MERAH (15)
  { komoditas: 'Cabai Rawit Merah', nama: 'Ori 212', produsen: 'Aura Seed', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '85-90 HST', potensiHasil: '10-15 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Tahan virus kuning, buah lebat, sangat disukai petani untuk musim kemarau maupun hujan.', kekurangan: 'Ukuran buah relatif lebih kecil dibandingkan varietas hibrida lainnya.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Kaliber', produsen: 'Jogja Seed', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan'], umurPanen: '80-90 HST', potensiHasil: '10-15 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Buah keras, tahan simpan dan angkut, warna merah cerah mengkilap, tahan rontok.', kekurangan: 'Kurang tahan terhadap curah hujan ekstrem, rentan antraknosa jika drainase buruk.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Bara', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '80-85 HST', potensiHasil: '10-15 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Tingkat kepedasan sangat tinggi, adaptasi luas di dataran rendah, buah tipe merunduk.', kekurangan: 'Umur panen sedikit lebih lambat, buah rentan rontok saat kemarau panjang tanpa penyiraman.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Pelita 8 F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-80 HST', potensiHasil: '10-15 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Produktivitas tinggi, bisa dipanen hijau maupun merah, toleran layu bakteri.', kekurangan: 'Kebutuhan pupuk dasar cukup tinggi untuk mencapai potensi maksimal.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Rompis F1', produsen: 'Mutiara Bumi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '85-90 HST', potensiHasil: '10-15 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Tahan antraknosa (patek), genjah, hasil per tanaman sangat tinggi.', kekurangan: 'Cabang kurang kokoh, butuh lanjaran ekstra kuat.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Shypoon', produsen: 'Halbanero', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan'], umurPanen: '80-90 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Ukuran buah panjang dan besar, bobot berat, vigor tanaman kuat.', kekurangan: 'Sangat rentan terhadap layu fusarium pada musim hujan.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Taruna', produsen: 'Bisi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan'], umurPanen: '80-90 HST', potensiHasil: '10-15 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Rawit tipe tegak, sangat pedas, toleran layu dan penyakit daun.', kekurangan: 'Buah tegak rentan masuknya air hujan sehingga mudah busuk.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Dewata 43 F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '65-70 HST', potensiHasil: '12-15 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Umur panen genjah (65 HST), warna buah kuning kehijauan lalu merah cerah.', kekurangan: 'Ukuran buah mengecil di masa panen akhir.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Sret', produsen: 'Bintang Asia', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-80 HST', potensiHasil: '10-15 ton/ha', harga: 'Rp 120.000 / 10gr', keunggulan: 'Buah sangat lebat, tahan layu fusarium, pedas menyengat.', kekurangan: 'Perlu pewiwillan intensif di awal masa tanam.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Pilar F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-80 HST', potensiHasil: '10-15 ton/ha', harga: 'Rp 145.000 / 10gr', keunggulan: 'Toleran virus kuning, sangat genjah, tahan rontok bunga.', kekurangan: 'Warna buah sedikit kusam jika kurang unsur Kalium.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Mhanu F1', produsen: 'Mutiara Bumi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '85-90 HST', potensiHasil: '12-16 ton/ha', harga: 'Rp 130.000 / 10gr', keunggulan: 'Tipe buah menggantung, produksi tinggi, warna merah menyala.', kekurangan: 'Daya simpan kurang lama, cepat mengkerut setelah dipetik.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Bhakti', produsen: 'Bisi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '80-85 HST', potensiHasil: '12-15 ton/ha', harga: 'Rp 115.000 / 10gr', keunggulan: 'Toleran kekeringan, perawatan mudah, buah lebat.', kekurangan: 'Rentan bercak daun jika musim hujan.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Saka', produsen: 'Aura Seed', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan'], umurPanen: '85-90 HST', potensiHasil: '14-18 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Buah besar, panjang, merah merata, tahan pengiriman jauh.', kekurangan: 'Kurang genjah, panen cukup lambat.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Sonar', produsen: 'Bisi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-85 HST', potensiHasil: '10-15 ton/ha', harga: 'Rp 125.000 / 10gr', keunggulan: 'Buah kecil namun super padat, rasa sangat pedas, toleran virus.', kekurangan: 'Pemetikan membutuhkan waktu lama karena buah kecil.' },
  { komoditas: 'Cabai Rawit Merah', nama: 'Pusaka 18', produsen: 'Tunas Agro', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '80-85 HST', potensiHasil: '13-16 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Tahan layu fusarium, warna merah cerah, tipe tumbuh tegak.', kekurangan: 'Batang kurang kokoh, wajib dipasang ajir sejak awal.' },

  // CABAI MERAH KERITING (15)
  { komoditas: 'Cabai Merah Keriting', nama: 'Laba F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-85 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Ukuran buah seragam, tahan layu bakteri, umur panen genjah.', kekurangan: 'Panjang buah berkurang pada dataran yang terlalu tinggi.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Lado F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '75-85 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Warna buah merah menyala, potensi hasil sangat tinggi, toleran kemarau.', kekurangan: 'Rentan keriting daun jika terserang thrips.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Akar', produsen: 'Mutiara Bumi', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-85 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Tahan cuaca ekstrem, sangat tahan penyakit antraknosa (patek).', kekurangan: 'Pertumbuhan awal agak lambat.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'OR Twist 42', produsen: 'Oriental Seed', ketinggian: ['Rendah', 'Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-85 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Adaptasi sangat luas, buah keriting sempurna, disukai pasar tradisional.', kekurangan: 'Sangat membutuhkan suplai kalsium agar ujung buah tidak busuk.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Lolai F1', produsen: 'Bintang Asia', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-85 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Tahan virus, buah lebat, panjang buah seragam hingga pucuk.', kekurangan: 'Kurang tahan genangan air.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Kastilo F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-85 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Toleran layu bakteri dan busuk batang, umur genjah, hasil tinggi.', kekurangan: 'Bobot per buah lebih ringan dibanding kompetitor.' },
  { mag: 'Cabai Merah Keriting', nama: 'Rempak F1', produsen: 'Bisi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-85 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Tahan Gemini Virus, panjang buah 15-17 cm, tekstur buah padat.', kekurangan: 'Banyak tunas air yang tumbuh, butuh tenaga kerja lebih untuk merempel.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Iggo', produsen: 'Bisi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-85 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Toleran penyakit layu bakteri dan antraknosa (patek).', kekurangan: 'Warna merah buah agak telat merata.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Tangguh F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-85 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Tahan patek (antraknosa), daya simpan kuat, tahan jarak jauh.', kekurangan: 'Ukuran buah sedikit lebih pendek.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Lotanbar', produsen: 'Halbanero', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '80-85 HST', potensiHasil: '16-22 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Potensi percabangan sangat banyak, tahan suhu panas ekstrim.', kekurangan: 'Warna buah sedikit memudar bila terlalu sering terpapar sinar matahari langsung tanpa daun pelindung.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Elegance', produsen: 'Known You Seed', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan'], umurPanen: '85-90 HST', potensiHasil: '15-18 ton/ha', harga: 'Rp 160.000 / 10gr', keunggulan: 'Kualitas buah ekspor, panjang, lurus, dan sangat merah mengkilap.', kekurangan: 'Benih relatif mahal, butuh perawatan ekstra agar lurus sempurna.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Rimba', produsen: 'Bintang Asia', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-80 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 120.000 / 10gr', keunggulan: 'Tanaman tegak, kokoh, tahan rebah, buah lebat.', kekurangan: 'Kulit buah cenderung tipis.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Jacko 99', produsen: 'Tunas Agro', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '80-85 HST', potensiHasil: '14-18 ton/ha', harga: 'Rp 130.000 / 10gr', keunggulan: 'Toleran layu bakteri, daun relatif kebal dari serangan kutu.', kekurangan: 'Panjang buah tidak maksimal pada lahan kering kerontang.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Sios Tavi', produsen: 'Bisi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-85 HST', potensiHasil: '16-20 ton/ha', harga: 'Rp 145.000 / 10gr', keunggulan: 'Sangat tahan virus (TAVI), daun hijau gelap, umur panen sangat panjang.', kekurangan: 'Tanaman sangat tinggi, butuh jarak tanam lebih lebar.' },
  { komoditas: 'Cabai Merah Keriting', nama: 'Kiyo F1', produsen: 'Mutiara Bumi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '80-85 HST', potensiHasil: '15-18 ton/ha', harga: 'Rp 135.000 / 10gr', keunggulan: 'Bentuk keritingnya tajam, sangat disukai pasar, tahan patek.', kekurangan: 'Daun agak rentan terhadap bercak daun cercospora.' },

  // CABAI MERAH BESAR (5)
  { komoditas: 'Cabai Merah Besar', nama: 'Gada F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '75-80 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 150.000 / 10gr', keunggulan: 'Ukuran buah sangat besar dan tebal, bobot berat.', kekurangan: 'Rentan patek saat musim hujan, harga pasar sangat fluktuatif.' },
  { komoditas: 'Cabai Merah Besar', nama: 'Columbus', produsen: 'Bisi', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '80-85 HST', potensiHasil: '16-22 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Tahan layu fusarium, warna merah tua, panjang.', kekurangan: 'Banyak tunas air.' },
  { komoditas: 'Cabai Merah Besar', nama: 'Baja F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-80 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 150.000 / 10gr', keunggulan: 'Tahan layu bakteri, cocok di dataran rendah.', kekurangan: 'Membutuhkan kalsium ekstra.' },
  { komoditas: 'Cabai Merah Besar', nama: 'Arimbi', produsen: 'Bisi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '80-85 HST', potensiHasil: '18-22 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Tahan virus, warna buah mengkilap, tebal.', kekurangan: 'Pertumbuhan agak lambat di awal.' },
  { komoditas: 'Cabai Merah Besar', nama: 'Horison', produsen: 'Known You Seed', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Kemarau'], umurPanen: '85-90 HST', potensiHasil: '15-20 ton/ha', harga: 'Rp 160.000 / 10gr', keunggulan: 'Kualitas buah premium ekspor, tebal dan keras.', kekurangan: 'Benih mahal dan butuh perawatan intensif.' },

  // TOMAT (10)
  { komoditas: 'Tomat', nama: 'Servo F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '60-70 HST', potensiHasil: '50-60 ton/ha', harga: 'Rp 165.000 / 10gr', keunggulan: 'Sangat tahan virus kuning (Gemini), ukuran buah sedang-besar, tahan simpan lama.', kekurangan: 'Daun lebat, membutuhkan pemangkasan rutin agar sirkulasi udara baik.' },
  { komoditas: 'Tomat', nama: 'Gustavi F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '60-70 HST', potensiHasil: '55-65 ton/ha', harga: 'Rp 170.000 / 10gr', keunggulan: 'Ukuran buah sangat besar dan seragam, daging tebal, tahan virus.', kekurangan: 'Tanaman bisa patah karena beban buah jika tiang lanjaran kurang kuat.' },
  { komoditas: 'Tomat', nama: 'Fortuna 23', produsen: 'Bisi', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '70-75 HST', potensiHasil: '60-70 ton/ha', harga: 'Rp 150.000 / 10gr', keunggulan: 'Produktivitas sangat tinggi di dataran tinggi, buah bulat keras.', kekurangan: 'Sangat rentan virus kuning jika ditanam di dataran rendah.' },
  { komoditas: 'Tomat', nama: 'Betavila F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '60-70 HST', potensiHasil: '45-55 ton/ha', harga: 'Rp 160.000 / 10gr', keunggulan: 'Toleran layu bakteri, umur panen genjah, rasa buah sedikit asam (cocok untuk sambal).', kekurangan: 'Buah rentan pecah jika penyiraman tidak konsisten (kadang kering kadang tergenang).' },
  { komoditas: 'Tomat', nama: 'TM Marvel', produsen: 'Tani Murni', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-80 HST', potensiHasil: '60-80 ton/ha', harga: 'Rp 180.000 / 10gr', keunggulan: 'Sangat toleran penyakit busuk daun (Phytophthora), buah besar-besar, warna merah merata.', kekurangan: 'Harga benih mahal, umur panen lebih lambat.' },
  { komoditas: 'Tomat', nama: 'Tyrana', produsen: 'Bisi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '65-70 HST', potensiHasil: '50-60 ton/ha', harga: 'Rp 150.000 / 10gr', keunggulan: 'Tahan virus kuning, buah keras, cocok untuk pasar jarak jauh.', kekurangan: 'Ukuran buah di tandan atas seringkali mengecil drastis.' },
  { komoditas: 'Tomat', nama: 'Optima F1', produsen: 'Bintang Asia', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '65-70 HST', potensiHasil: '55-65 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Vigor kuat, tandan buah rapat, warna buah merah cerah.', kekurangan: 'Agak peka terhadap bercak daun septoria.' },
  { komoditas: 'Tomat', nama: 'Marta F1', produsen: 'Panah Merah', ketinggian: ['Menengah', 'Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '70-80 HST', potensiHasil: '60-70 ton/ha', harga: 'Rp 155.000 / 10gr', keunggulan: 'Buah sangat keras dan tahan angkut jarak jauh (antar pulau).', kekurangan: 'Kurang cocok untuk dataran rendah (mudah gugur bunga).' },
  { komoditas: 'Tomat', nama: 'Amala F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '65-70 HST', potensiHasil: '50-60 ton/ha', harga: 'Rp 160.000 / 10gr', keunggulan: 'Tahan Gemini Virus dan layu bakteri, adaptasi luas.', kekurangan: 'Kulit buah agak tebal.' },
  { komoditas: 'Tomat', nama: 'Corona', produsen: 'Known You Seed', ketinggian: ['Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '80-85 HST', potensiHasil: '70-90 ton/ha', harga: 'Rp 200.000 / 10gr', keunggulan: 'Buah premium ekspor (tipe beef tomato), ukuran sangat raksasa.', kekurangan: 'Sangat rawan busuk pantat buah jika kalsium minim.' },

  // BAWANG MERAH (5)
  { komoditas: 'Bawang Merah', nama: 'Sanren F1 (Biji)', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '65-70 HST', potensiHasil: '20-25 ton/ha', harga: 'Rp 280.000 / 50gr', keunggulan: 'Ditanam dari biji (TSS), bebas penyakit bawaan umbi, umbi besar dan padat.', kekurangan: 'Persemaian biji membutuhkan ketelitian ekstra tinggi.' },
  { komoditas: 'Bawang Merah', nama: 'Tuk Tuk (Biji)', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '65-70 HST', potensiHasil: '20-25 ton/ha', harga: 'Rp 250.000 / 50gr', keunggulan: 'Ditanam dari biji, umbi bulat, toleran cuaca buruk.', kekurangan: 'Proses penyemaian biji rumit untuk pemula.' },
  { komoditas: 'Bawang Merah', nama: 'Bima Brebes', produsen: 'Lokal/Umbi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '55-60 HST', potensiHasil: '10-15 ton/ha', harga: 'Fluktuatif', keunggulan: 'Aroma sangat tajam, warna merah keunguan pekat, disukai pasar.', kekurangan: 'Rentan penyakit layu fusarium (mboler) jika ditanam di musim hujan.' },
  { komoditas: 'Bawang Merah', nama: 'Bauji', produsen: 'Lokal/Umbi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '60-65 HST', potensiHasil: '12-18 ton/ha', harga: 'Fluktuatif', keunggulan: 'Sangat toleran curah hujan tinggi, tahan penyakit pucuk pucat.', kekurangan: 'Aroma kurang setajam Bima Brebes, warna agak kusam.' },
  { komoditas: 'Bawang Merah', nama: 'Tajuk', produsen: 'Lokal/Umbi', ketinggian: ['Rendah'], cuaca: ['Kemarau'], umurPanen: '55-60 HST', potensiHasil: '12-16 ton/ha', harga: 'Fluktuatif', keunggulan: 'Umur genjah, warna umbi merah merona, daun keras.', kekurangan: 'Kurang tahan hujan lebat, mudah rebah.' },

  // MENTIMUN (5)
  { komoditas: 'Mentimun', nama: 'Zatavy F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '35-40 HST', potensiHasil: '40-50 ton/ha', harga: 'Rp 65.000 / 20gr', keunggulan: 'Sangat genjah, toleran virus kuning, warna buah hijau gelap merata.', kekurangan: 'Buah bagian bawah kadang bengkok jika kurang unsur kalium.' },
  { komoditas: 'Mentimun', nama: 'Vanesa', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '35-40 HST', potensiHasil: '40-50 ton/ha', harga: 'Rp 65.000 / 20gr', keunggulan: 'Buah hijau cerah, lurus, renyah (cocok untuk lalapan).', kekurangan: 'Rentan embun bulu saat kelembaban sangat tinggi.' },
  { komoditas: 'Mentimun', nama: 'Hercules Plus', produsen: 'Bisi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '38-42 HST', potensiHasil: '50-60 ton/ha', harga: 'Rp 70.000 / 20gr', keunggulan: 'Vigor tanaman sangat kuat, buah besar, tahan embun bulu (Downy Mildew).', kekurangan: 'Daun sangat lebar, rawan tumbang jika lanjaran tidak kuat.' },
  { komoditas: 'Mentimun', nama: 'Ethana F1', produsen: 'Panah Merah', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '35-40 HST', potensiHasil: '40-50 ton/ha', harga: 'Rp 75.000 / 20gr', keunggulan: 'Toleran virus gemini, umur genjah, bentuk silindris rata.', kekurangan: 'Cabang samping terlalu lebat, butuh perempelan.' },
  { komoditas: 'Mentimun', nama: 'Metavy', produsen: 'Bisi', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '35-42 HST', potensiHasil: '45-55 ton/ha', harga: 'Rp 75.000 / 20gr', keunggulan: 'Tahan virus kuning (TAVI), kulit buah tebal, tahan simpan dan angkut.', kekurangan: 'Warna buah terlalu gelap bagi sebagian selera pasar.' },

  // KUBIS (Sawi/Kol) (5)
  { komoditas: 'Kubis', nama: 'Green Nova', produsen: 'Takii Seed', ketinggian: ['Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '75-80 HST', potensiHasil: '45-55 ton/ha', harga: 'Rp 140.000 / 10gr', keunggulan: 'Tahan penyakit busuk hitam, kepala sangat padat, bulat pipih.', kekurangan: 'Hanya bisa ditanam di dataran tinggi, di dataran rendah tidak mau membentuk krop.' },
  { komoditas: 'Kubis', nama: 'Grand 11', produsen: 'Known You Seed', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '60-65 HST', potensiHasil: '35-40 ton/ha', harga: 'Rp 110.000 / 10gr', keunggulan: 'Bisa membentuk krop di dataran rendah yang panas.', kekurangan: 'Krop lebih kecil dan kurang padat dibanding kubis dataran tinggi.' },
  { komoditas: 'Kubis', nama: 'KK Cross', produsen: 'Takii Seed', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Kemarau'], umurPanen: '60-65 HST', potensiHasil: '35-45 ton/ha', harga: 'Rp 120.000 / 10gr', keunggulan: 'Toleran panas, umur genjah, hasil tinggi di dataran menengah.', kekurangan: 'Rentan penyakit busuk lunak bakteri saat musim hujan.' },
  { komoditas: 'Kubis', nama: 'Sehati', produsen: 'Bintang Asia', ketinggian: ['Rendah', 'Menengah'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '65-70 HST', potensiHasil: '35-45 ton/ha', harga: 'Rp 100.000 / 10gr', keunggulan: 'Krop padat untuk ukuran kubis dataran rendah, tahan panas.', kekurangan: 'Daya simpan kurang lama.' },
  { komoditas: 'Kubis', nama: 'Ijo Lumut', produsen: 'Panah Merah', ketinggian: ['Tinggi'], cuaca: ['Hujan', 'Kemarau'], umurPanen: '70-75 HST', potensiHasil: '45-55 ton/ha', harga: 'Rp 130.000 / 10gr', keunggulan: 'Warna krop hijau mengkilat, sangat padat, tahan busuk hitam.', kekurangan: 'Tidak toleran terhadap suhu panas berlebih.' }
];`

const startIndex = content.indexOf('const CATALOG = [');
const endIndex = content.indexOf('];', startIndex) + 2;

content = content.substring(0, startIndex) + newCatalog + content.substring(endIndex);

// Add the typo fix in komoditas: 'mag' to 'komoditas'
content = content.replace(/mag: 'Cabai Merah Keriting'/g, "komoditas: 'Cabai Merah Keriting'");

fs.writeFileSync('src/views/CariBibitView.tsx', content);
